/**
 *  Autogenerated class
 */
package org.c3s.edgo.common.beans;

import java.io.Serializable;
import java.util.*;
import org.c3s.db.beans.DbBean;
import org.c3s.data.annotations.DataSource;
import org.c3s.data.annotations.DataTarget;
import org.c3s.reflection.annotation.*;


public class DBActivityBean implements DbBean, Serializable {

	private static final long serialVersionUID = 1L;


	
	@DataSource({"times", "times"})
	@DataTarget("times")
	@XMLSimple("times")
	private java.lang.Long times;
	
	public java.lang.Long getTimes() {
		return times;
	}
	
	public DBActivityBean setTimes(java.lang.Long value) {
		times = value;
		return this;
	}
	
	
	@DataSource({"event_date", "eventDate"})
	@DataTarget("event_date")
	@XMLSimple("eventDate")
	private java.lang.Long eventDate;
	
	public java.lang.Long getEventDate() {
		return eventDate;
	}
	
	public DBActivityBean setEventDate(java.lang.Long value) {
		eventDate = value;
		return this;
	}
	
	@Override
	public void setAutoincrementField(Object value) {
		
	}	
	
}