/**
 *  Autogenerated class
 */
package org.c3s.edgo.common.beans;

import java.io.Serializable;
import java.util.*;
import org.c3s.db.beans.DbBean;
import org.c3s.data.annotations.DataSource;
import org.c3s.data.annotations.DataTarget;
import org.c3s.reflection.annotation.*;


public class DBActivityBean implements DbBean, Serializable {

	private static final long serialVersionUID = 1L;


	
	@DataSource({"times", "times"})
	@DataTarget("times")
	@XMLSimple("times")
	private java.math.BigDecimal times;
	
	public java.math.BigDecimal getTimes() {
		return times;
	}
	
	public DBActivityBean setTimes(java.math.BigDecimal value) {
		this.times = value;
		return this;
	}
	
	
	@DataSource({"times_group", "timesGroup"})
	@DataTarget("times_group")
	@XMLSimple("timesGroup")
	private java.math.BigDecimal timesGroup;
	
	public java.math.BigDecimal getTimesGroup() {
		return timesGroup;
	}
	
	public DBActivityBean setTimesGroup(java.math.BigDecimal value) {
		this.timesGroup = value;
		return this;
	}
	
	
	@DataSource({"times_solo", "timesSolo"})
	@DataTarget("times_solo")
	@XMLSimple("timesSolo")
	private java.math.BigDecimal timesSolo;
	
	public java.math.BigDecimal getTimesSolo() {
		return timesSolo;
	}
	
	public DBActivityBean setTimesSolo(java.math.BigDecimal value) {
		this.timesSolo = value;
		return this;
	}
	
	
	@DataSource({"event_date", "eventDate"})
	@DataTarget("event_date")
	@XMLSimple("eventDate")
	private java.lang.Integer eventDate;
	
	public java.lang.Integer getEventDate() {
		return eventDate;
	}
	
	public DBActivityBean setEventDate(java.lang.Integer value) {
		this.eventDate = value;
		return this;
	}
	
	
	@DataSource({"times_open", "timesOpen"})
	@DataTarget("times_open")
	@XMLSimple("timesOpen")
	private java.math.BigDecimal timesOpen;
	
	public java.math.BigDecimal getTimesOpen() {
		return timesOpen;
	}
	
	public DBActivityBean setTimesOpen(java.math.BigDecimal value) {
		this.timesOpen = value;
		return this;
	}
	
	@Override
	public void setAutoincrementField(Object value) {
		
	}	
	
}