/**
 *  Autogenerated class
 */
package org.c3s.edgo.common.beans;

import java.io.Serializable;
import java.util.*;
import org.c3s.db.beans.DbBean;
import org.c3s.data.annotations.DataSource;
import org.c3s.data.annotations.DataTarget;
import org.c3s.reflection.annotation.*;


public class DBByUniqBean implements DbBean, Serializable {

	private static final long serialVersionUID = 1L;


	
	@DataSource({"module_group_id", "moduleGroupId"})
	@DataTarget("module_group_id")
	@XMLSimple("moduleGroupId")
	private java.lang.Long moduleGroupId;
	
	public java.lang.Long getModuleGroupId() {
		return moduleGroupId;
	}
	
	public DBByUniqBean setModuleGroupId(java.lang.Long value) {
		moduleGroupId = value;
		return this;
	}
	
	
	@DataSource({"module_rating", "moduleRating"})
	@DataTarget("module_rating")
	@XMLSimple("moduleRating")
	private java.lang.String moduleRating;
	
	public java.lang.String getModuleRating() {
		return moduleRating;
	}
	
	public DBByUniqBean setModuleRating(java.lang.String value) {
		moduleRating = value;
		return this;
	}
	
	
	@DataSource({"module_id", "moduleId"})
	@DataTarget("module_id")
	@XMLSimple("moduleId")
	private java.lang.Long moduleId;
	
	public java.lang.Long getModuleId() {
		return moduleId;
	}
	
	public DBByUniqBean setModuleId(java.lang.Long value) {
		moduleId = value;
		return this;
	}
	
	
	@DataSource({"module_name", "moduleName"})
	@DataTarget("module_name")
	@XMLSimple("moduleName")
	private java.lang.String moduleName;
	
	public java.lang.String getModuleName() {
		return moduleName;
	}
	
	public DBByUniqBean setModuleName(java.lang.String value) {
		moduleName = value;
		return this;
	}
	
	
	@DataSource({"module_uniq", "moduleUniq"})
	@DataTarget("module_uniq")
	@XMLSimple("moduleUniq")
	private java.lang.String moduleUniq;
	
	public java.lang.String getModuleUniq() {
		return moduleUniq;
	}
	
	public DBByUniqBean setModuleUniq(java.lang.String value) {
		moduleUniq = value;
		return this;
	}
	
	
	@DataSource({"module_class", "moduleClass"})
	@DataTarget("module_class")
	@XMLSimple("moduleClass")
	private java.lang.Integer moduleClass;
	
	public java.lang.Integer getModuleClass() {
		return moduleClass;
	}
	
	public DBByUniqBean setModuleClass(java.lang.Integer value) {
		moduleClass = value;
		return this;
	}
	
	@Override
	public void setAutoincrementField(Object value) {
		
	}	
	
}