/**
 *  Autogenerated class
 */
package org.c3s.edgo.common.beans;

import java.io.Serializable;
import java.util.*;
import org.c3s.db.beans.DbBean;
import org.c3s.data.annotations.DataSource;
import org.c3s.data.annotations.DataTarget;
import org.c3s.reflection.annotation.*;


public class DBByPilotIdAndLinkShipIdWithLocationBean implements DbBean, Serializable {

	private static final long serialVersionUID = 1L;


	
	@DataSource({"station_name", "stationName"})
	@DataTarget("name")
	@XMLSimple("stationName")
	private java.lang.String stationName;
	
	public java.lang.String getStationName() {
		return stationName;
	}
	
	public DBByPilotIdAndLinkShipIdWithLocationBean setStationName(java.lang.String value) {
		this.stationName = value;
		return this;
	}
	
	
	@DataSource({"link_ship_id", "linkShipId"})
	@DataTarget("link_ship_id")
	@XMLSimple("linkShipId")
	private java.lang.Long linkShipId;
	
	public java.lang.Long getLinkShipId() {
		return linkShipId;
	}
	
	public DBByPilotIdAndLinkShipIdWithLocationBean setLinkShipId(java.lang.Long value) {
		this.linkShipId = value;
		return this;
	}
	
	
	@DataSource({"pilot_ship_id", "pilotShipId"})
	@DataTarget("pilot_ship_id")
	@XMLSimple("pilotShipId")
	private java.lang.Long pilotShipId;
	
	public java.lang.Long getPilotShipId() {
		return pilotShipId;
	}
	
	public DBByPilotIdAndLinkShipIdWithLocationBean setPilotShipId(java.lang.Long value) {
		this.pilotShipId = value;
		return this;
	}
	
	
	@DataSource({"system_id", "systemId"})
	@DataTarget("system_id")
	@XMLSimple("systemId")
	private java.math.BigInteger systemId;
	
	public java.math.BigInteger getSystemId() {
		return systemId;
	}
	
	public DBByPilotIdAndLinkShipIdWithLocationBean setSystemId(java.math.BigInteger value) {
		this.systemId = value;
		return this;
	}
	
	
	@DataSource({"station_id", "stationId"})
	@DataTarget("station_id")
	@XMLSimple("stationId")
	private java.lang.Long stationId;
	
	public java.lang.Long getStationId() {
		return stationId;
	}
	
	public DBByPilotIdAndLinkShipIdWithLocationBean setStationId(java.lang.Long value) {
		this.stationId = value;
		return this;
	}
	
	
	@DataSource({"system_name", "systemName"})
	@DataTarget("name")
	@XMLSimple("systemName")
	private java.lang.String systemName;
	
	public java.lang.String getSystemName() {
		return systemName;
	}
	
	public DBByPilotIdAndLinkShipIdWithLocationBean setSystemName(java.lang.String value) {
		this.systemName = value;
		return this;
	}
	
	
	@DataSource({"can_deleted", "canDeleted"})
	@DataTarget("can_deleted")
	@XMLSimple("canDeleted")
	private java.lang.Integer canDeleted;
	
	public java.lang.Integer getCanDeleted() {
		return canDeleted;
	}
	
	public DBByPilotIdAndLinkShipIdWithLocationBean setCanDeleted(java.lang.Integer value) {
		this.canDeleted = value;
		return this;
	}
	
	
	@DataSource({"pilot_id", "pilotId"})
	@DataTarget("pilot_id")
	@XMLSimple("pilotId")
	private java.lang.Long pilotId;
	
	public java.lang.Long getPilotId() {
		return pilotId;
	}
	
	public DBByPilotIdAndLinkShipIdWithLocationBean setPilotId(java.lang.Long value) {
		this.pilotId = value;
		return this;
	}
	
	
	@DataSource({"pilot_ship_ident", "pilotShipIdent"})
	@DataTarget("pilot_ship_ident")
	@XMLSimple("pilotShipIdent")
	private java.lang.String pilotShipIdent;
	
	public java.lang.String getPilotShipIdent() {
		return pilotShipIdent;
	}
	
	public DBByPilotIdAndLinkShipIdWithLocationBean setPilotShipIdent(java.lang.String value) {
		this.pilotShipIdent = value;
		return this;
	}
	
	
	@DataSource({"is_main", "isMain"})
	@DataTarget("is_main")
	@XMLSimple("isMain")
	private java.lang.Integer isMain;
	
	public java.lang.Integer getIsMain() {
		return isMain;
	}
	
	public DBByPilotIdAndLinkShipIdWithLocationBean setIsMain(java.lang.Integer value) {
		this.isMain = value;
		return this;
	}
	
	
	@DataSource({"ship_id", "shipId"})
	@DataTarget("ship_id")
	@XMLSimple("shipId")
	private java.lang.Long shipId;
	
	public java.lang.Long getShipId() {
		return shipId;
	}
	
	public DBByPilotIdAndLinkShipIdWithLocationBean setShipId(java.lang.Long value) {
		this.shipId = value;
		return this;
	}
	
	
	@DataSource({"pilot_ship_name", "pilotShipName"})
	@DataTarget("pilot_ship_name")
	@XMLSimple("pilotShipName")
	private java.lang.String pilotShipName;
	
	public java.lang.String getPilotShipName() {
		return pilotShipName;
	}
	
	public DBByPilotIdAndLinkShipIdWithLocationBean setPilotShipName(java.lang.String value) {
		this.pilotShipName = value;
		return this;
	}
	
	@Override
	public void setAutoincrementField(Object value) {
		
		setPilotShipId(new java.lang.Long(value.toString()));
		
	}	
	
}