/**
 *  Autogenerated class
 */
package org.c3s.edgo.common.beans;

import java.io.Serializable;
import java.util.*;
import org.c3s.db.beans.DbBean;
import org.c3s.data.annotations.DataSource;
import org.c3s.data.annotations.DataTarget;
import org.c3s.reflection.annotation.*;


public class DBEngGradeBean implements DbBean, Serializable {

	private static final long serialVersionUID = 1L;


	
	@DataSource({"eng_blueprint_id", "engBlueprintId"})
	@DataTarget("eng_blueprint_id")
	@XMLSimple("engBlueprintId")
	private java.lang.Long engBlueprintId;
	
	public java.lang.Long getEngBlueprintId() {
		return engBlueprintId;
	}
	
	public DBEngGradeBean setEngBlueprintId(java.lang.Long value) {
		this.engBlueprintId = value;
		return this;
	}
	
	
	@DataSource({"eng_grade_id", "engGradeId"})
	@DataTarget("eng_grade_id")
	@XMLSimple("engGradeId")
	private java.lang.Long engGradeId;
	
	public java.lang.Long getEngGradeId() {
		return engGradeId;
	}
	
	public DBEngGradeBean setEngGradeId(java.lang.Long value) {
		this.engGradeId = value;
		return this;
	}
	
	
	@DataSource({"grade", "grade"})
	@DataTarget("grade")
	@XMLSimple("grade")
	private java.lang.Long grade;
	
	public java.lang.Long getGrade() {
		return grade;
	}
	
	public DBEngGradeBean setGrade(java.lang.Long value) {
		this.grade = value;
		return this;
	}
	
	@Override
	public void setAutoincrementField(Object value) {
		
		setEngGradeId(new java.lang.Long(value.toString()));
		
	}	
	
}