/**
 *  Autogenerated class
 */
package org.c3s.edgo.common.beans;

import java.io.Serializable;
import java.util.*;
import org.c3s.db.beans.DbBean;
import org.c3s.data.annotations.DataSource;
import org.c3s.data.annotations.DataTarget;
import org.c3s.reflection.annotation.*;


public class DBFullEventsListBean implements DbBean, Serializable {

	private static final long serialVersionUID = 1L;


	
	@DataSource({"list", "list"})
	@DataTarget("list")
	@XMLSimple("list")
	private java.lang.String list;
	
	public java.lang.String getList() {
		return list;
	}
	
	public DBFullEventsListBean setList(java.lang.String value) {
		this.list = value;
		return this;
	}
	
	@Override
	public void setAutoincrementField(Object value) {
		
	}	
	
}