/**
 *  Autogenerated class
 */
package org.c3s.edgo.common.beans;

import java.io.Serializable;
import java.util.*;
import org.c3s.db.beans.DbBean;
import org.c3s.data.annotations.DataSource;
import org.c3s.data.annotations.DataTarget;
import org.c3s.reflection.annotation.*;


public class DBImageConfigsBean implements DbBean, Serializable {

	private static final long serialVersionUID = 1L;


	
	@DataSource({"config_name", "configName"})
	@DataTarget("config_name")
	@XMLSimple("configName")
	private java.lang.String configName;
	
	public java.lang.String getConfigName() {
		return configName;
	}
	
	public DBImageConfigsBean setConfigName(java.lang.String value) {
		this.configName = value;
		return this;
	}
	
	
	@DataSource({"is_active", "isActive"})
	@DataTarget("is_active")
	@XMLSimple("isActive")
	private java.lang.Integer isActive;
	
	public java.lang.Integer getIsActive() {
		return isActive;
	}
	
	public DBImageConfigsBean setIsActive(java.lang.Integer value) {
		this.isActive = value;
		return this;
	}
	
	
	@DataSource({"create_time", "createTime"})
	@DataTarget("create_time")
	@XMLSimple("createTime")
	private java.sql.Timestamp createTime;
	
	public java.sql.Timestamp getCreateTime() {
		return createTime;
	}
	
	public DBImageConfigsBean setCreateTime(java.sql.Timestamp value) {
		this.createTime = value;
		return this;
	}
	
	
	@DataSource({"max_height", "maxHeight"})
	@DataTarget("max_height")
	@XMLSimple("maxHeight")
	private java.lang.Long maxHeight;
	
	public java.lang.Long getMaxHeight() {
		return maxHeight;
	}
	
	public DBImageConfigsBean setMaxHeight(java.lang.Long value) {
		this.maxHeight = value;
		return this;
	}
	
	
	@DataSource({"type", "type"})
	@DataTarget("type")
	@XMLSimple("type")
	private java.lang.String type;
	
	public java.lang.String getType() {
		return type;
	}
	
	public DBImageConfigsBean setType(java.lang.String value) {
		this.type = value;
		return this;
	}
	
	
	@DataSource({"can_scale", "canScale"})
	@DataTarget("can_scale")
	@XMLSimple("canScale")
	private java.lang.Integer canScale;
	
	public java.lang.Integer getCanScale() {
		return canScale;
	}
	
	public DBImageConfigsBean setCanScale(java.lang.Integer value) {
		this.canScale = value;
		return this;
	}
	
	
	@DataSource({"quality", "quality"})
	@DataTarget("quality")
	@XMLSimple("quality")
	private java.lang.Integer quality;
	
	public java.lang.Integer getQuality() {
		return quality;
	}
	
	public DBImageConfigsBean setQuality(java.lang.Integer value) {
		this.quality = value;
		return this;
	}
	
	
	@DataSource({"max_width", "maxWidth"})
	@DataTarget("max_width")
	@XMLSimple("maxWidth")
	private java.lang.Long maxWidth;
	
	public java.lang.Long getMaxWidth() {
		return maxWidth;
	}
	
	public DBImageConfigsBean setMaxWidth(java.lang.Long value) {
		this.maxWidth = value;
		return this;
	}
	
	
	@DataSource({"can_crop", "canCrop"})
	@DataTarget("can_crop")
	@XMLSimple("canCrop")
	private java.lang.Integer canCrop;
	
	public java.lang.Integer getCanCrop() {
		return canCrop;
	}
	
	public DBImageConfigsBean setCanCrop(java.lang.Integer value) {
		this.canCrop = value;
		return this;
	}
	
	
	@DataSource({"is_auto", "isAuto"})
	@DataTarget("is_auto")
	@XMLSimple("isAuto")
	private java.lang.Integer isAuto;
	
	public java.lang.Integer getIsAuto() {
		return isAuto;
	}
	
	public DBImageConfigsBean setIsAuto(java.lang.Integer value) {
		this.isAuto = value;
		return this;
	}
	
	
	@DataSource({"update_time", "updateTime"})
	@DataTarget("update_time")
	@XMLSimple("updateTime")
	private java.sql.Timestamp updateTime;
	
	public java.sql.Timestamp getUpdateTime() {
		return updateTime;
	}
	
	public DBImageConfigsBean setUpdateTime(java.sql.Timestamp value) {
		this.updateTime = value;
		return this;
	}
	
	
	@DataSource({"min_height", "minHeight"})
	@DataTarget("min_height")
	@XMLSimple("minHeight")
	private java.lang.Long minHeight;
	
	public java.lang.Long getMinHeight() {
		return minHeight;
	}
	
	public DBImageConfigsBean setMinHeight(java.lang.Long value) {
		this.minHeight = value;
		return this;
	}
	
	
	@DataSource({"config_id", "configId"})
	@DataTarget("config_id")
	@XMLSimple("configId")
	private java.lang.Long configId;
	
	public java.lang.Long getConfigId() {
		return configId;
	}
	
	public DBImageConfigsBean setConfigId(java.lang.Long value) {
		this.configId = value;
		return this;
	}
	
	
	@DataSource({"min_width", "minWidth"})
	@DataTarget("min_width")
	@XMLSimple("minWidth")
	private java.lang.Long minWidth;
	
	public java.lang.Long getMinWidth() {
		return minWidth;
	}
	
	public DBImageConfigsBean setMinWidth(java.lang.Long value) {
		this.minWidth = value;
		return this;
	}
	
	@Override
	public void setAutoincrementField(Object value) {
		
		setConfigId(new java.lang.Long(value.toString()));
		
	}	
	
}