/**
 *  Autogenerated class
 */
package org.c3s.edgo.common.beans;

import java.io.Serializable;
import java.util.*;
import org.c3s.db.beans.DbBean;
import org.c3s.data.annotations.DataSource;
import org.c3s.data.annotations.DataTarget;
import org.c3s.reflection.annotation.*;


public class DBLastEventForUserBean implements DbBean, Serializable {

	private static final long serialVersionUID = 1L;


	
	@DataSource({"used_names", "usedNames"})
	@DataTarget("used_names")
	@XMLSimple("usedNames")
	private java.lang.String usedNames;
	
	public java.lang.String getUsedNames() {
		return usedNames;
	}
	
	public DBLastEventForUserBean setUsedNames(java.lang.String value) {
		usedNames = value;
		return this;
	}
	
	
	@DataSource({"event", "event"})
	@DataTarget("event_name")
	@XMLSimple("event")
	private java.lang.String event;
	
	public java.lang.String getEvent() {
		return event;
	}
	
	public DBLastEventForUserBean setEvent(java.lang.String value) {
		event = value;
		return this;
	}
	
	
	@DataSource({"hash", "hash"})
	@DataTarget("event_hash")
	@XMLSimple("hash")
	private java.lang.String hash;
	
	public java.lang.String getHash() {
		return hash;
	}
	
	public DBLastEventForUserBean setHash(java.lang.String value) {
		hash = value;
		return this;
	}
	
	
	@DataSource({"timestamp", "timestamp"})
	@DataTarget("timestamp")
	@XMLSimple("timestamp")
	private java.lang.String timestamp;
	
	public java.lang.String getTimestamp() {
		return timestamp;
	}
	
	public DBLastEventForUserBean setTimestamp(java.lang.String value) {
		timestamp = value;
		return this;
	}
	
	@Override
	public void setAutoincrementField(Object value) {
		
	}	
	
}