/**
 *  Autogenerated class
 */
package org.c3s.edgo.common.beans;

import java.io.Serializable;
import java.util.*;
import org.c3s.db.beans.DbBean;
import org.c3s.data.annotations.DataSource;
import org.c3s.data.annotations.DataTarget;
import org.c3s.reflection.annotation.*;


public class DBLastLocationForPilotBean implements DbBean, Serializable {

	private static final long serialVersionUID = 1L;


	
	@DataSource({"station_name", "stationName"})
	@DataTarget("name")
	@XMLSimple("stationName")
	private java.lang.String stationName;
	
	public java.lang.String getStationName() {
		return stationName;
	}
	
	public DBLastLocationForPilotBean setStationName(java.lang.String value) {
		stationName = value;
		return this;
	}
	
	
	@DataSource({"system_id", "systemId"})
	@DataTarget("system_id")
	@XMLSimple("systemId")
	private java.math.BigInteger systemId;
	
	public java.math.BigInteger getSystemId() {
		return systemId;
	}
	
	public DBLastLocationForPilotBean setSystemId(java.math.BigInteger value) {
		systemId = value;
		return this;
	}
	
	
	@DataSource({"station_id", "stationId"})
	@DataTarget("station_id")
	@XMLSimple("stationId")
	private java.lang.Long stationId;
	
	public java.lang.Long getStationId() {
		return stationId;
	}
	
	public DBLastLocationForPilotBean setStationId(java.lang.Long value) {
		stationId = value;
		return this;
	}
	
	
	@DataSource({"system_name", "systemName"})
	@DataTarget("name")
	@XMLSimple("systemName")
	private java.lang.String systemName;
	
	public java.lang.String getSystemName() {
		return systemName;
	}
	
	public DBLastLocationForPilotBean setSystemName(java.lang.String value) {
		systemName = value;
		return this;
	}
	
	
	@DataSource({"pilot_id", "pilotId"})
	@DataTarget("pilot_id")
	@XMLSimple("pilotId")
	private java.lang.Long pilotId;
	
	public java.lang.Long getPilotId() {
		return pilotId;
	}
	
	public DBLastLocationForPilotBean setPilotId(java.lang.Long value) {
		pilotId = value;
		return this;
	}
	
	
	@DataSource({"location_id", "locationId"})
	@DataTarget("location_id")
	@XMLSimple("locationId")
	private java.math.BigInteger locationId;
	
	public java.math.BigInteger getLocationId() {
		return locationId;
	}
	
	public DBLastLocationForPilotBean setLocationId(java.math.BigInteger value) {
		locationId = value;
		return this;
	}
	
	
	@DataSource({"location_time", "locationTime"})
	@DataTarget("location_time")
	@XMLSimple("locationTime")
	private java.sql.Timestamp locationTime;
	
	public java.sql.Timestamp getLocationTime() {
		return locationTime;
	}
	
	public DBLastLocationForPilotBean setLocationTime(java.sql.Timestamp value) {
		locationTime = value;
		return this;
	}
	
	@Override
	public void setAutoincrementField(Object value) {
		
		setLocationId(new java.math.BigInteger(value.toString()));
		
	}	
	
}