/**
 *  Autogenerated class
 */
package org.c3s.edgo.common.beans;

import java.io.Serializable;
import java.util.*;
import org.c3s.db.beans.DbBean;
import org.c3s.data.annotations.DataSource;
import org.c3s.data.annotations.DataTarget;
import org.c3s.reflection.annotation.*;


public class DBLastSystemFactionStateBean implements DbBean, Serializable {

	private static final long serialVersionUID = 1L;


	
	@DataSource({"system_id", "systemId"})
	@DataTarget("system_id")
	@XMLSimple("systemId")
	private java.math.BigInteger systemId;
	
	public java.math.BigInteger getSystemId() {
		return systemId;
	}
	
	public DBLastSystemFactionStateBean setSystemId(java.math.BigInteger value) {
		this.systemId = value;
		return this;
	}
	
	
	@DataSource({"uniq", "uniq"})
	@DataTarget("uniq")
	@XMLSimple("uniq")
	private java.lang.String uniq;
	
	public java.lang.String getUniq() {
		return uniq;
	}
	
	public DBLastSystemFactionStateBean setUniq(java.lang.String value) {
		this.uniq = value;
		return this;
	}
	
	
	@DataSource({"pending_states", "pendingStates"})
	@DataTarget("pending_states")
	@XMLSimple("pendingStates")
	private java.lang.String pendingStates;
	
	public java.lang.String getPendingStates() {
		return pendingStates;
	}
	
	public DBLastSystemFactionStateBean setPendingStates(java.lang.String value) {
		this.pendingStates = value;
		return this;
	}
	
	
	@DataSource({"faction_id", "factionId"})
	@DataTarget("faction_id")
	@XMLSimple("factionId")
	private java.lang.Long factionId;
	
	public java.lang.Long getFactionId() {
		return factionId;
	}
	
	public DBLastSystemFactionStateBean setFactionId(java.lang.Long value) {
		this.factionId = value;
		return this;
	}
	
	
	@DataSource({"state_id", "stateId"})
	@DataTarget("state_id")
	@XMLSimple("stateId")
	private java.lang.Long stateId;
	
	public java.lang.Long getStateId() {
		return stateId;
	}
	
	public DBLastSystemFactionStateBean setStateId(java.lang.Long value) {
		this.stateId = value;
		return this;
	}
	
	
	@DataSource({"create_date", "createDate"})
	@DataTarget("create_date")
	@XMLSimple("createDate")
	private java.sql.Timestamp createDate;
	
	public java.sql.Timestamp getCreateDate() {
		return createDate;
	}
	
	public DBLastSystemFactionStateBean setCreateDate(java.sql.Timestamp value) {
		this.createDate = value;
		return this;
	}
	
	
	@DataSource({"recovery_states", "recoveryStates"})
	@DataTarget("recovery_states")
	@XMLSimple("recoveryStates")
	private java.lang.String recoveryStates;
	
	public java.lang.String getRecoveryStates() {
		return recoveryStates;
	}
	
	public DBLastSystemFactionStateBean setRecoveryStates(java.lang.String value) {
		this.recoveryStates = value;
		return this;
	}
	
	
	@DataSource({"update_date", "updateDate"})
	@DataTarget("update_date")
	@XMLSimple("updateDate")
	private java.sql.Timestamp updateDate;
	
	public java.sql.Timestamp getUpdateDate() {
		return updateDate;
	}
	
	public DBLastSystemFactionStateBean setUpdateDate(java.sql.Timestamp value) {
		this.updateDate = value;
		return this;
	}
	
	
	@DataSource({"system_factions_history_id", "systemFactionsHistoryId"})
	@DataTarget("system_factions_history_id")
	@XMLSimple("systemFactionsHistoryId")
	private java.math.BigInteger systemFactionsHistoryId;
	
	public java.math.BigInteger getSystemFactionsHistoryId() {
		return systemFactionsHistoryId;
	}
	
	public DBLastSystemFactionStateBean setSystemFactionsHistoryId(java.math.BigInteger value) {
		this.systemFactionsHistoryId = value;
		return this;
	}
	
	
	@DataSource({"influence", "influence"})
	@DataTarget("influence")
	@XMLSimple("influence")
	private java.lang.Float influence;
	
	public java.lang.Float getInfluence() {
		return influence;
	}
	
	public DBLastSystemFactionStateBean setInfluence(java.lang.Float value) {
		this.influence = value;
		return this;
	}
	
	@Override
	public void setAutoincrementField(Object value) {
		
		setSystemFactionsHistoryId(new java.math.BigInteger(value.toString()));
		
	}	
	
}