/**
 *  Autogenerated class
 */
package org.c3s.edgo.common.beans;

import java.io.Serializable;
import java.util.*;
import org.c3s.db.beans.DbBean;
import org.c3s.data.annotations.DataSource;
import org.c3s.data.annotations.DataTarget;
import org.c3s.reflection.annotation.*;


public class DBMaxMinDateSystemHistoryForPilotBean implements DbBean, Serializable {

	private static final long serialVersionUID = 1L;


	
	@DataSource({"max_date", "maxDate"})
	@DataTarget("max_date")
	@XMLSimple("maxDate")
	private java.lang.String maxDate;
	
	public java.lang.String getMaxDate() {
		return maxDate;
	}
	
	public DBMaxMinDateSystemHistoryForPilotBean setMaxDate(java.lang.String value) {
		maxDate = value;
		return this;
	}
	
	
	@DataSource({"min_date", "minDate"})
	@DataTarget("min_date")
	@XMLSimple("minDate")
	private java.lang.String minDate;
	
	public java.lang.String getMinDate() {
		return minDate;
	}
	
	public DBMaxMinDateSystemHistoryForPilotBean setMinDate(java.lang.String value) {
		minDate = value;
		return this;
	}
	
	
	@DataSource({"pilot_id", "pilotId"})
	@DataTarget("pilot_id")
	@XMLSimple("pilotId")
	private java.lang.Long pilotId;
	
	public java.lang.Long getPilotId() {
		return pilotId;
	}
	
	public DBMaxMinDateSystemHistoryForPilotBean setPilotId(java.lang.Long value) {
		pilotId = value;
		return this;
	}
	
	@Override
	public void setAutoincrementField(Object value) {
		
		setPilotId(new java.lang.Long(value.toString()));
		
	}	
	
}