/**
 *  Autogenerated class
 */
package org.c3s.edgo.common.beans;

import java.io.Serializable;
import java.util.*;
import org.c3s.db.beans.DbBean;
import org.c3s.data.annotations.DataSource;
import org.c3s.data.annotations.DataTarget;
import org.c3s.reflection.annotation.*;


public class DBMaterialUnsingInfoBean implements DbBean, Serializable {

	private static final long serialVersionUID = 1L;


	
	@DataSource({"eng_blueprint_id", "engBlueprintId"})
	@DataTarget("eng_blueprint_id")
	@XMLSimple("engBlueprintId")
	private java.lang.Long engBlueprintId;
	
	public java.lang.Long getEngBlueprintId() {
		return engBlueprintId;
	}
	
	public DBMaterialUnsingInfoBean setEngBlueprintId(java.lang.Long value) {
		this.engBlueprintId = value;
		return this;
	}
	
	
	@DataSource({"engeneers", "engeneers"})
	@DataTarget("engeneers")
	@XMLSimple("engeneers")
	private java.lang.String engeneers;
	
	public java.lang.String getEngeneers() {
		return engeneers;
	}
	
	public DBMaterialUnsingInfoBean setEngeneers(java.lang.String value) {
		this.engeneers = value;
		return this;
	}
	
	
	@DataSource({"eng_type_name", "engTypeName"})
	@DataTarget("eng_type_name")
	@XMLSimple("engTypeName")
	private java.lang.String engTypeName;
	
	public java.lang.String getEngTypeName() {
		return engTypeName;
	}
	
	public DBMaterialUnsingInfoBean setEngTypeName(java.lang.String value) {
		this.engTypeName = value;
		return this;
	}
	
	
	@DataSource({"material_loc", "materialLoc"})
	@DataTarget("material_loc")
	@XMLSimple("materialLoc")
	private java.lang.String materialLoc;
	
	public java.lang.String getMaterialLoc() {
		return materialLoc;
	}
	
	public DBMaterialUnsingInfoBean setMaterialLoc(java.lang.String value) {
		this.materialLoc = value;
		return this;
	}
	
	
	@DataSource({"eng_type_uniq", "engTypeUniq"})
	@DataTarget("eng_type_uniq")
	@XMLSimple("engTypeUniq")
	private java.lang.String engTypeUniq;
	
	public java.lang.String getEngTypeUniq() {
		return engTypeUniq;
	}
	
	public DBMaterialUnsingInfoBean setEngTypeUniq(java.lang.String value) {
		this.engTypeUniq = value;
		return this;
	}
	
	
	@DataSource({"eng_grade_id", "engGradeId"})
	@DataTarget("eng_grade_id")
	@XMLSimple("engGradeId")
	private java.lang.Long engGradeId;
	
	public java.lang.Long getEngGradeId() {
		return engGradeId;
	}
	
	public DBMaterialUnsingInfoBean setEngGradeId(java.lang.Long value) {
		this.engGradeId = value;
		return this;
	}
	
	
	@DataSource({"eng_blueprint_uniq", "engBlueprintUniq"})
	@DataTarget("eng_blueprint_uniq")
	@XMLSimple("engBlueprintUniq")
	private java.lang.String engBlueprintUniq;
	
	public java.lang.String getEngBlueprintUniq() {
		return engBlueprintUniq;
	}
	
	public DBMaterialUnsingInfoBean setEngBlueprintUniq(java.lang.String value) {
		this.engBlueprintUniq = value;
		return this;
	}
	
	
	@DataSource({"grade", "grade"})
	@DataTarget("grade")
	@XMLSimple("grade")
	private java.lang.Long grade;
	
	public java.lang.Long getGrade() {
		return grade;
	}
	
	public DBMaterialUnsingInfoBean setGrade(java.lang.Long value) {
		this.grade = value;
		return this;
	}
	
	
	@DataSource({"eng_type_id", "engTypeId"})
	@DataTarget("eng_type_id")
	@XMLSimple("engTypeId")
	private java.lang.Long engTypeId;
	
	public java.lang.Long getEngTypeId() {
		return engTypeId;
	}
	
	public DBMaterialUnsingInfoBean setEngTypeId(java.lang.Long value) {
		this.engTypeId = value;
		return this;
	}
	
	
	@DataSource({"material_uniq", "materialUniq"})
	@DataTarget("material_uniq")
	@XMLSimple("materialUniq")
	private java.lang.String materialUniq;
	
	public java.lang.String getMaterialUniq() {
		return materialUniq;
	}
	
	public DBMaterialUnsingInfoBean setMaterialUniq(java.lang.String value) {
		this.materialUniq = value;
		return this;
	}
	
	
	@DataSource({"eng_blueprint_name", "engBlueprintName"})
	@DataTarget("eng_blueprint_name")
	@XMLSimple("engBlueprintName")
	private java.lang.String engBlueprintName;
	
	public java.lang.String getEngBlueprintName() {
		return engBlueprintName;
	}
	
	public DBMaterialUnsingInfoBean setEngBlueprintName(java.lang.String value) {
		this.engBlueprintName = value;
		return this;
	}
	
	@Override
	public void setAutoincrementField(Object value) {
		
		setEngBlueprintId(new java.lang.Long(value.toString()));
		
		setEngGradeId(new java.lang.Long(value.toString()));
		
		setEngTypeId(new java.lang.Long(value.toString()));
		
	}	
	
}