/**
 *  Autogenerated class
 */
package org.c3s.edgo.common.beans;

import java.io.Serializable;
import java.util.*;
import org.c3s.db.beans.DbBean;
import org.c3s.data.annotations.DataSource;
import org.c3s.data.annotations.DataTarget;
import org.c3s.reflection.annotation.*;


public class DBMenuPilotsByUserIdBean implements DbBean, Serializable {

	private static final long serialVersionUID = 1L;


	
	@DataSource({"parent_pilot_id", "parentPilotId"})
	@DataTarget("parent_pilot_id")
	@XMLSimple("parentPilotId")
	private java.lang.Long parentPilotId;
	
	public java.lang.Long getParentPilotId() {
		return parentPilotId;
	}
	
	public DBMenuPilotsByUserIdBean setParentPilotId(java.lang.Long value) {
		this.parentPilotId = value;
		return this;
	}
	
	
	@DataSource({"user_id", "userId"})
	@DataTarget("user_id")
	@XMLSimple("userId")
	private java.lang.Long userId;
	
	public java.lang.Long getUserId() {
		return userId;
	}
	
	public DBMenuPilotsByUserIdBean setUserId(java.lang.Long value) {
		this.userId = value;
		return this;
	}
	
	
	@DataSource({"pilot_name", "pilotName"})
	@DataTarget("pilot_name")
	@XMLSimple("pilotName")
	private java.lang.String pilotName;
	
	public java.lang.String getPilotName() {
		return pilotName;
	}
	
	public DBMenuPilotsByUserIdBean setPilotName(java.lang.String value) {
		this.pilotName = value;
		return this;
	}
	
	
	@DataSource({"is_current", "isCurrent"})
	@DataTarget("is_current")
	@XMLSimple("isCurrent")
	private java.lang.Integer isCurrent;
	
	public java.lang.Integer getIsCurrent() {
		return isCurrent;
	}
	
	public DBMenuPilotsByUserIdBean setIsCurrent(java.lang.Integer value) {
		this.isCurrent = value;
		return this;
	}
	
	
	@DataSource({"pilot_id", "pilotId"})
	@DataTarget("pilot_id")
	@XMLSimple("pilotId")
	private java.lang.Long pilotId;
	
	public java.lang.Long getPilotId() {
		return pilotId;
	}
	
	public DBMenuPilotsByUserIdBean setPilotId(java.lang.Long value) {
		this.pilotId = value;
		return this;
	}
	
	
	@DataSource({"is_ignored", "isIgnored"})
	@DataTarget("is_ignored")
	@XMLSimple("isIgnored")
	private java.lang.Integer isIgnored;
	
	public java.lang.Integer getIsIgnored() {
		return isIgnored;
	}
	
	public DBMenuPilotsByUserIdBean setIsIgnored(java.lang.Integer value) {
		this.isIgnored = value;
		return this;
	}
	
	@Override
	public void setAutoincrementField(Object value) {
		
		setPilotId(new java.lang.Long(value.toString()));
		
	}	
	
}