/**
 *  Autogenerated class
 */
package org.c3s.edgo.common.beans;

import java.io.Serializable;
import java.util.*;
import org.c3s.db.beans.DbBean;
import org.c3s.data.annotations.DataSource;
import org.c3s.data.annotations.DataTarget;
import org.c3s.reflection.annotation.*;


public class DBMissionFactionEffectsBean implements DbBean, Serializable {

	private static final long serialVersionUID = 1L;


	
	@DataSource({"mission_id", "missionId"})
	@DataTarget("mission_id")
	@XMLSimple("missionId")
	private java.math.BigInteger missionId;
	
	public java.math.BigInteger getMissionId() {
		return missionId;
	}
	
	public DBMissionFactionEffectsBean setMissionId(java.math.BigInteger value) {
		this.missionId = value;
		return this;
	}
	
	
	@DataSource({"reputation", "reputation"})
	@DataTarget("reputation")
	@XMLSimple("reputation")
	private java.lang.String reputation;
	
	public java.lang.String getReputation() {
		return reputation;
	}
	
	public DBMissionFactionEffectsBean setReputation(java.lang.String value) {
		this.reputation = value;
		return this;
	}
	
	
	@DataSource({"faction_id", "factionId"})
	@DataTarget("faction_id")
	@XMLSimple("factionId")
	private java.lang.Long factionId;
	
	public java.lang.Long getFactionId() {
		return factionId;
	}
	
	public DBMissionFactionEffectsBean setFactionId(java.lang.Long value) {
		this.factionId = value;
		return this;
	}
	
	
	@DataSource({"mission_faction_effect_id", "missionFactionEffectId"})
	@DataTarget("mission_faction_effect_id")
	@XMLSimple("missionFactionEffectId")
	private java.math.BigInteger missionFactionEffectId;
	
	public java.math.BigInteger getMissionFactionEffectId() {
		return missionFactionEffectId;
	}
	
	public DBMissionFactionEffectsBean setMissionFactionEffectId(java.math.BigInteger value) {
		this.missionFactionEffectId = value;
		return this;
	}
	
	@Override
	public void setAutoincrementField(Object value) {
		
		setMissionFactionEffectId(new java.math.BigInteger(value.toString()));
		
	}	
	
}