/**
 *  Autogenerated class
 */
package org.c3s.edgo.common.beans;

import java.io.Serializable;
import java.util.*;
import org.c3s.db.beans.DbBean;
import org.c3s.data.annotations.DataSource;
import org.c3s.data.annotations.DataTarget;
import org.c3s.reflection.annotation.*;


public class DBMissionFactionInfluenceBean implements DbBean, Serializable {

	private static final long serialVersionUID = 1L;


	
	@DataSource({"trend", "trend"})
	@DataTarget("trend")
	@XMLSimple("trend")
	private java.lang.String trend;
	
	public java.lang.String getTrend() {
		return trend;
	}
	
	public DBMissionFactionInfluenceBean setTrend(java.lang.String value) {
		this.trend = value;
		return this;
	}
	
	
	@DataSource({"system_address", "systemAddress"})
	@DataTarget("system_address")
	@XMLSimple("systemAddress")
	private java.math.BigInteger systemAddress;
	
	public java.math.BigInteger getSystemAddress() {
		return systemAddress;
	}
	
	public DBMissionFactionInfluenceBean setSystemAddress(java.math.BigInteger value) {
		this.systemAddress = value;
		return this;
	}
	
	
	@DataSource({"mission_faction_effect_id", "missionFactionEffectId"})
	@DataTarget("mission_faction_effect_id")
	@XMLSimple("missionFactionEffectId")
	private java.math.BigInteger missionFactionEffectId;
	
	public java.math.BigInteger getMissionFactionEffectId() {
		return missionFactionEffectId;
	}
	
	public DBMissionFactionInfluenceBean setMissionFactionEffectId(java.math.BigInteger value) {
		this.missionFactionEffectId = value;
		return this;
	}
	
	
	@DataSource({"influence", "influence"})
	@DataTarget("influence")
	@XMLSimple("influence")
	private java.lang.String influence;
	
	public java.lang.String getInfluence() {
		return influence;
	}
	
	public DBMissionFactionInfluenceBean setInfluence(java.lang.String value) {
		this.influence = value;
		return this;
	}
	
	@Override
	public void setAutoincrementField(Object value) {
		
	}	
	
}