/**
 *  Autogenerated class
 */
package org.c3s.edgo.common.beans;

import java.io.Serializable;
import java.util.*;
import org.c3s.db.beans.DbBean;
import org.c3s.data.annotations.DataSource;
import org.c3s.data.annotations.DataTarget;
import org.c3s.reflection.annotation.*;


public class DBModuleEffectsBean implements DbBean, Serializable {

	private static final long serialVersionUID = 1L;


	
	@DataSource({"effect_uniq", "effectUniq"})
	@DataTarget("effect_uniq")
	@XMLSimple("effectUniq")
	private java.lang.String effectUniq;
	
	public java.lang.String getEffectUniq() {
		return effectUniq;
	}
	
	public DBModuleEffectsBean setEffectUniq(java.lang.String value) {
		this.effectUniq = value;
		return this;
	}
	
	
	@DataSource({"effect_id", "effectId"})
	@DataTarget("effect_id")
	@XMLSimple("effectId")
	private java.lang.Long effectId;
	
	public java.lang.Long getEffectId() {
		return effectId;
	}
	
	public DBModuleEffectsBean setEffectId(java.lang.Long value) {
		this.effectId = value;
		return this;
	}
	
	@Override
	public void setAutoincrementField(Object value) {
		
		setEffectId(new java.lang.Long(value.toString()));
		
	}	
	
}