/**
 *  Autogenerated class
 */
package org.c3s.edgo.common.beans;

import java.io.Serializable;
import java.util.*;
import org.c3s.db.beans.DbBean;
import org.c3s.data.annotations.DataSource;
import org.c3s.data.annotations.DataTarget;
import org.c3s.reflection.annotation.*;


public class DBModifiersBean implements DbBean, Serializable {

	private static final long serialVersionUID = 1L;


	
	@DataSource({"modifier_name", "modifierName"})
	@DataTarget("modifier_name")
	@XMLSimple("modifierName")
	private java.lang.String modifierName;
	
	public java.lang.String getModifierName() {
		return modifierName;
	}
	
	public DBModifiersBean setModifierName(java.lang.String value) {
		this.modifierName = value;
		return this;
	}
	
	
	@DataSource({"modifier_id", "modifierId"})
	@DataTarget("modifier_id")
	@XMLSimple("modifierId")
	private java.lang.Long modifierId;
	
	public java.lang.Long getModifierId() {
		return modifierId;
	}
	
	public DBModifiersBean setModifierId(java.lang.Long value) {
		this.modifierId = value;
		return this;
	}
	
	
	@DataSource({"modifier_uniq", "modifierUniq"})
	@DataTarget("modifier_uniq")
	@XMLSimple("modifierUniq")
	private java.lang.String modifierUniq;
	
	public java.lang.String getModifierUniq() {
		return modifierUniq;
	}
	
	public DBModifiersBean setModifierUniq(java.lang.String value) {
		this.modifierUniq = value;
		return this;
	}
	
	@Override
	public void setAutoincrementField(Object value) {
		
		setModifierId(new java.lang.Long(value.toString()));
		
	}	
	
}