/**
 *  Autogenerated class
 */
package org.c3s.edgo.common.beans;

import java.io.Serializable;
import java.util.*;
import org.c3s.db.beans.DbBean;
import org.c3s.data.annotations.DataSource;
import org.c3s.data.annotations.DataTarget;
import org.c3s.reflection.annotation.*;


public class DBPilotsRelationsBean implements DbBean, Serializable {

	private static final long serialVersionUID = 1L;


	
	@DataSource({"is_me", "isMe"})
	@DataTarget("is_me")
	@XMLSimple("isMe")
	private java.lang.Long isMe;
	
	public java.lang.Long getIsMe() {
		return isMe;
	}
	
	public DBPilotsRelationsBean setIsMe(java.lang.Long value) {
		isMe = value;
		return this;
	}
	
	
	@DataSource({"relation", "relation"})
	@DataTarget("relation")
	@XMLSimple("relation")
	private java.lang.Long relation;
	
	public java.lang.Long getRelation() {
		return relation;
	}
	
	public DBPilotsRelationsBean setRelation(java.lang.Long value) {
		relation = value;
		return this;
	}
	
	@Override
	public void setAutoincrementField(Object value) {
		
	}	
	
}