/**
 *  Autogenerated class
 */
package org.c3s.edgo.common.beans;

import java.io.Serializable;
import java.util.*;
import org.c3s.db.beans.DbBean;
import org.c3s.data.annotations.DataSource;
import org.c3s.data.annotations.DataTarget;
import org.c3s.reflection.annotation.*;


public class DBPilotShipsListBean implements DbBean, Serializable {

	private static final long serialVersionUID = 1L;


	
	@DataSource({"station_name", "stationName"})
	@DataTarget("name")
	@XMLSimple("stationName")
	private java.lang.String stationName;
	
	public java.lang.String getStationName() {
		return stationName;
	}
	
	public DBPilotShipsListBean setStationName(java.lang.String value) {
		this.stationName = value;
		return this;
	}
	
	
	@DataSource({"link_ship_id", "linkShipId"})
	@DataTarget("link_ship_id")
	@XMLSimple("linkShipId")
	private java.lang.Long linkShipId;
	
	public java.lang.Long getLinkShipId() {
		return linkShipId;
	}
	
	public DBPilotShipsListBean setLinkShipId(java.lang.Long value) {
		this.linkShipId = value;
		return this;
	}
	
	
	@DataSource({"pilot_ship_id", "pilotShipId"})
	@DataTarget("pilot_ship_id")
	@XMLSimple("pilotShipId")
	private java.lang.Long pilotShipId;
	
	public java.lang.Long getPilotShipId() {
		return pilotShipId;
	}
	
	public DBPilotShipsListBean setPilotShipId(java.lang.Long value) {
		this.pilotShipId = value;
		return this;
	}
	
	
	@DataSource({"system_id", "systemId"})
	@DataTarget("system_id")
	@XMLSimple("systemId")
	private java.math.BigInteger systemId;
	
	public java.math.BigInteger getSystemId() {
		return systemId;
	}
	
	public DBPilotShipsListBean setSystemId(java.math.BigInteger value) {
		this.systemId = value;
		return this;
	}
	
	
	@DataSource({"station_id", "stationId"})
	@DataTarget("station_id")
	@XMLSimple("stationId")
	private java.lang.Long stationId;
	
	public java.lang.Long getStationId() {
		return stationId;
	}
	
	public DBPilotShipsListBean setStationId(java.lang.Long value) {
		this.stationId = value;
		return this;
	}
	
	
	@DataSource({"system_name", "systemName"})
	@DataTarget("name")
	@XMLSimple("systemName")
	private java.lang.String systemName;
	
	public java.lang.String getSystemName() {
		return systemName;
	}
	
	public DBPilotShipsListBean setSystemName(java.lang.String value) {
		this.systemName = value;
		return this;
	}
	
	
	@DataSource({"can_deleted", "canDeleted"})
	@DataTarget("can_deleted")
	@XMLSimple("canDeleted")
	private java.lang.Integer canDeleted;
	
	public java.lang.Integer getCanDeleted() {
		return canDeleted;
	}
	
	public DBPilotShipsListBean setCanDeleted(java.lang.Integer value) {
		this.canDeleted = value;
		return this;
	}
	
	
	@DataSource({"pilot_id", "pilotId"})
	@DataTarget("pilot_id")
	@XMLSimple("pilotId")
	private java.lang.Long pilotId;
	
	public java.lang.Long getPilotId() {
		return pilotId;
	}
	
	public DBPilotShipsListBean setPilotId(java.lang.Long value) {
		this.pilotId = value;
		return this;
	}
	
	
	@DataSource({"ship_uniq", "shipUniq"})
	@DataTarget("ship_uniq")
	@XMLSimple("shipUniq")
	private java.lang.String shipUniq;
	
	public java.lang.String getShipUniq() {
		return shipUniq;
	}
	
	public DBPilotShipsListBean setShipUniq(java.lang.String value) {
		this.shipUniq = value;
		return this;
	}
	
	
	@DataSource({"is_special", "isSpecial"})
	@DataTarget("is_special")
	@XMLSimple("isSpecial")
	private java.lang.Integer isSpecial;
	
	public java.lang.Integer getIsSpecial() {
		return isSpecial;
	}
	
	public DBPilotShipsListBean setIsSpecial(java.lang.Integer value) {
		this.isSpecial = value;
		return this;
	}
	
	
	@DataSource({"eddb_id", "eddbId"})
	@DataTarget("eddb_id")
	@XMLSimple("eddbId")
	private java.lang.Long eddbId;
	
	public java.lang.Long getEddbId() {
		return eddbId;
	}
	
	public DBPilotShipsListBean setEddbId(java.lang.Long value) {
		this.eddbId = value;
		return this;
	}
	
	
	@DataSource({"pilot_ship_ident", "pilotShipIdent"})
	@DataTarget("pilot_ship_ident")
	@XMLSimple("pilotShipIdent")
	private java.lang.String pilotShipIdent;
	
	public java.lang.String getPilotShipIdent() {
		return pilotShipIdent;
	}
	
	public DBPilotShipsListBean setPilotShipIdent(java.lang.String value) {
		this.pilotShipIdent = value;
		return this;
	}
	
	
	@DataSource({"is_main", "isMain"})
	@DataTarget("is_main")
	@XMLSimple("isMain")
	private java.lang.Integer isMain;
	
	public java.lang.Integer getIsMain() {
		return isMain;
	}
	
	public DBPilotShipsListBean setIsMain(java.lang.Integer value) {
		this.isMain = value;
		return this;
	}
	
	
	@DataSource({"x", "x"})
	@DataTarget("x")
	@XMLSimple("x")
	private java.lang.Double x;
	
	public java.lang.Double getX() {
		return x;
	}
	
	public DBPilotShipsListBean setX(java.lang.Double value) {
		this.x = value;
		return this;
	}
	
	
	@DataSource({"y", "y"})
	@DataTarget("y")
	@XMLSimple("y")
	private java.lang.Double y;
	
	public java.lang.Double getY() {
		return y;
	}
	
	public DBPilotShipsListBean setY(java.lang.Double value) {
		this.y = value;
		return this;
	}
	
	
	@DataSource({"z", "z"})
	@DataTarget("z")
	@XMLSimple("z")
	private java.lang.Double z;
	
	public java.lang.Double getZ() {
		return z;
	}
	
	public DBPilotShipsListBean setZ(java.lang.Double value) {
		this.z = value;
		return this;
	}
	
	
	@DataSource({"ship_name", "shipName"})
	@DataTarget("ship_name")
	@XMLSimple("shipName")
	private java.lang.String shipName;
	
	public java.lang.String getShipName() {
		return shipName;
	}
	
	public DBPilotShipsListBean setShipName(java.lang.String value) {
		this.shipName = value;
		return this;
	}
	
	
	@DataSource({"ship_id", "shipId"})
	@DataTarget("ship_id")
	@XMLSimple("shipId")
	private java.lang.Long shipId;
	
	public java.lang.Long getShipId() {
		return shipId;
	}
	
	public DBPilotShipsListBean setShipId(java.lang.Long value) {
		this.shipId = value;
		return this;
	}
	
	
	@DataSource({"pilot_ship_name", "pilotShipName"})
	@DataTarget("pilot_ship_name")
	@XMLSimple("pilotShipName")
	private java.lang.String pilotShipName;
	
	public java.lang.String getPilotShipName() {
		return pilotShipName;
	}
	
	public DBPilotShipsListBean setPilotShipName(java.lang.String value) {
		this.pilotShipName = value;
		return this;
	}
	
	
	@DataSource({"distance", "distance"})
	@DataTarget("distance")
	@XMLSimple

	private Double distance;
	
	public Double getDistance() {
		return distance;
	}
	
	public DBPilotShipsListBean setDistance(Double value) {
		this.distance = value;
		return this;
	}
	
	@Override
	public void setAutoincrementField(Object value) {
		
	}	
	
}