/**
 *  Autogenerated class
 */
package org.c3s.edgo.common.beans;

import java.io.Serializable;
import java.util.*;
import org.c3s.db.beans.DbBean;
import org.c3s.data.annotations.DataSource;
import org.c3s.data.annotations.DataTarget;
import org.c3s.reflection.annotation.*;


public class DBPilotsPowerWeeksBean implements DbBean, Serializable {

	private static final long serialVersionUID = 1L;


	
	@DataSource({"start_week", "startWeek"})
	@DataTarget("start_week")
	@XMLSimple("startWeek")
	private java.sql.Timestamp startWeek;
	
	public java.sql.Timestamp getStartWeek() {
		return startWeek;
	}
	
	public DBPilotsPowerWeeksBean setStartWeek(java.sql.Timestamp value) {
		this.startWeek = value;
		return this;
	}
	
	@Override
	public void setAutoincrementField(Object value) {
		
	}	
	
}