/**
 *  Autogenerated class
 */
package org.c3s.edgo.common.beans;

import java.io.Serializable;
import java.util.*;
import org.c3s.db.beans.DbBean;
import org.c3s.data.annotations.DataSource;
import org.c3s.data.annotations.DataTarget;
import org.c3s.reflection.annotation.*;


public class DBPilotLastInfoBean implements DbBean, Serializable {

	private static final long serialVersionUID = 1L;


	
	@DataSource({"loan", "loan"})
	@DataTarget("loan")
	@XMLSimple("loan")
	private java.math.BigInteger loan;
	
	public java.math.BigInteger getLoan() {
		return loan;
	}
	
	public DBPilotLastInfoBean setLoan(java.math.BigInteger value) {
		loan = value;
		return this;
	}
	
	
	@DataSource({"credits", "credits"})
	@DataTarget("credits")
	@XMLSimple("credits")
	private java.math.BigInteger credits;
	
	public java.math.BigInteger getCredits() {
		return credits;
	}
	
	public DBPilotLastInfoBean setCredits(java.math.BigInteger value) {
		credits = value;
		return this;
	}
	
	
	@DataSource({"game_mode", "gameMode"})
	@DataTarget("game_mode")
	@XMLSimple("gameMode")
	private java.lang.String gameMode;
	
	public java.lang.String getGameMode() {
		return gameMode;
	}
	
	public DBPilotLastInfoBean setGameMode(java.lang.String value) {
		gameMode = value;
		return this;
	}
	
	
	@DataSource({"pilot_id", "pilotId"})
	@DataTarget("pilot_id")
	@XMLSimple("pilotId")
	private java.lang.Long pilotId;
	
	public java.lang.Long getPilotId() {
		return pilotId;
	}
	
	public DBPilotLastInfoBean setPilotId(java.lang.Long value) {
		pilotId = value;
		return this;
	}
	
	
	@DataSource({"game_group", "gameGroup"})
	@DataTarget("game_group")
	@XMLSimple("gameGroup")
	private java.lang.String gameGroup;
	
	public java.lang.String getGameGroup() {
		return gameGroup;
	}
	
	public DBPilotLastInfoBean setGameGroup(java.lang.String value) {
		gameGroup = value;
		return this;
	}
	
	@Override
	public void setAutoincrementField(Object value) {
		
	}	
	
}