/**
 *  Autogenerated class
 */
package org.c3s.edgo.common.beans;

import java.io.Serializable;
import java.util.*;
import org.c3s.db.beans.DbBean;
import org.c3s.data.annotations.DataSource;
import org.c3s.data.annotations.DataTarget;
import org.c3s.reflection.annotation.*;


public class DBPilotsLastEventsBean implements DbBean, Serializable {

	private static final long serialVersionUID = 1L;


	
	@DataSource({"user_id", "userId"})
	@DataTarget("user_id")
	@XMLSimple("userId")
	private java.lang.Long userId;
	
	public java.lang.Long getUserId() {
		return userId;
	}
	
	public DBPilotsLastEventsBean setUserId(java.lang.Long value) {
		userId = value;
		return this;
	}
	
	
	@DataSource({"event_hash", "eventHash"})
	@DataTarget("event_hash")
	@XMLSimple("eventHash")
	private java.lang.String eventHash;
	
	public java.lang.String getEventHash() {
		return eventHash;
	}
	
	public DBPilotsLastEventsBean setEventHash(java.lang.String value) {
		eventHash = value;
		return this;
	}
	
	
	@DataSource({"event_name", "eventName"})
	@DataTarget("event_name")
	@XMLSimple("eventName")
	private java.lang.String eventName;
	
	public java.lang.String getEventName() {
		return eventName;
	}
	
	public DBPilotsLastEventsBean setEventName(java.lang.String value) {
		eventName = value;
		return this;
	}
	
	
	@DataSource({"event_timestamp", "eventTimestamp"})
	@DataTarget("event_timestamp")
	@XMLSimple("eventTimestamp")
	private java.sql.Timestamp eventTimestamp;
	
	public java.sql.Timestamp getEventTimestamp() {
		return eventTimestamp;
	}
	
	public DBPilotsLastEventsBean setEventTimestamp(java.sql.Timestamp value) {
		eventTimestamp = value;
		return this;
	}
	
	
	@DataSource({"pilot_id", "pilotId"})
	@DataTarget("pilot_id")
	@XMLSimple("pilotId")
	private java.lang.Long pilotId;
	
	public java.lang.Long getPilotId() {
		return pilotId;
	}
	
	public DBPilotsLastEventsBean setPilotId(java.lang.Long value) {
		pilotId = value;
		return this;
	}
	
	
	@DataSource({"events_history_id", "eventsHistoryId"})
	@DataTarget("events_history_id")
	@XMLSimple("eventsHistoryId")
	private java.math.BigInteger eventsHistoryId;
	
	public java.math.BigInteger getEventsHistoryId() {
		return eventsHistoryId;
	}
	
	public DBPilotsLastEventsBean setEventsHistoryId(java.math.BigInteger value) {
		eventsHistoryId = value;
		return this;
	}
	
	@Override
	public void setAutoincrementField(Object value) {
		
		setEventsHistoryId(new java.math.BigInteger(value.toString()));
		
	}	
	
}