/**
 *  Autogenerated class
 */
package org.c3s.edgo.common.beans;

import java.io.Serializable;
import java.util.*;
import org.c3s.db.beans.DbBean;
import org.c3s.data.annotations.DataSource;
import org.c3s.data.annotations.DataTarget;
import org.c3s.reflection.annotation.*;


public class DBPowerStateTypeBean implements DbBean, Serializable {

	private static final long serialVersionUID = 1L;


	
	@DataSource({"is_warzone", "isWarzone"})
	@DataTarget("is_warzone")
	@XMLSimple("isWarzone")
	private java.lang.Integer isWarzone;
	
	public java.lang.Integer getIsWarzone() {
		return isWarzone;
	}
	
	public DBPowerStateTypeBean setIsWarzone(java.lang.Integer value) {
		this.isWarzone = value;
		return this;
	}
	
	
	@DataSource({"power_state_type_id", "powerStateTypeId"})
	@DataTarget("power_state_type_id")
	@XMLSimple("powerStateTypeId")
	private java.lang.Long powerStateTypeId;
	
	public java.lang.Long getPowerStateTypeId() {
		return powerStateTypeId;
	}
	
	public DBPowerStateTypeBean setPowerStateTypeId(java.lang.Long value) {
		this.powerStateTypeId = value;
		return this;
	}
	
	
	@DataSource({"power_state_type_name", "powerStateTypeName"})
	@DataTarget("power_state_type_name")
	@XMLSimple("powerStateTypeName")
	private java.lang.String powerStateTypeName;
	
	public java.lang.String getPowerStateTypeName() {
		return powerStateTypeName;
	}
	
	public DBPowerStateTypeBean setPowerStateTypeName(java.lang.String value) {
		this.powerStateTypeName = value;
		return this;
	}
	
	
	@DataSource({"power_state_type_uniq", "powerStateTypeUniq"})
	@DataTarget("power_state_type_uniq")
	@XMLSimple("powerStateTypeUniq")
	private java.lang.String powerStateTypeUniq;
	
	public java.lang.String getPowerStateTypeUniq() {
		return powerStateTypeUniq;
	}
	
	public DBPowerStateTypeBean setPowerStateTypeUniq(java.lang.String value) {
		this.powerStateTypeUniq = value;
		return this;
	}
	
	
	@DataSource({"is_permanent", "isPermanent"})
	@DataTarget("is_permanent")
	@XMLSimple("isPermanent")
	private java.lang.Integer isPermanent;
	
	public java.lang.Integer getIsPermanent() {
		return isPermanent;
	}
	
	public DBPowerStateTypeBean setIsPermanent(java.lang.Integer value) {
		this.isPermanent = value;
		return this;
	}
	
	
	@DataSource({"is_merits", "isMerits"})
	@DataTarget("is_merits")
	@XMLSimple("isMerits")
	private java.lang.Integer isMerits;
	
	public java.lang.Integer getIsMerits() {
		return isMerits;
	}
	
	public DBPowerStateTypeBean setIsMerits(java.lang.Integer value) {
		this.isMerits = value;
		return this;
	}
	
	
	@DataSource({"is_weekly", "isWeekly"})
	@DataTarget("is_weekly")
	@XMLSimple("isWeekly")
	private java.lang.Integer isWeekly;
	
	public java.lang.Integer getIsWeekly() {
		return isWeekly;
	}
	
	public DBPowerStateTypeBean setIsWeekly(java.lang.Integer value) {
		this.isWeekly = value;
		return this;
	}
	
	@Override
	public void setAutoincrementField(Object value) {
		
		setPowerStateTypeId(new java.lang.Long(value.toString()));
		
	}	
	
}