/**
 *  Autogenerated class
 */
package org.c3s.edgo.common.beans;

import java.io.Serializable;
import java.util.*;
import org.c3s.db.beans.DbBean;
import org.c3s.data.annotations.DataSource;
import org.c3s.data.annotations.DataTarget;
import org.c3s.reflection.annotation.*;


public class DBSettlementTypesBean implements DbBean, Serializable {

	private static final long serialVersionUID = 1L;


	
	@DataSource({"settlement_type_id", "settlementTypeId"})
	@DataTarget("settlement_type_id")
	@XMLSimple("settlementTypeId")
	private java.lang.Long settlementTypeId;
	
	public java.lang.Long getSettlementTypeId() {
		return settlementTypeId;
	}
	
	public DBSettlementTypesBean setSettlementTypeId(java.lang.Long value) {
		this.settlementTypeId = value;
		return this;
	}
	
	
	@DataSource({"type", "type"})
	@DataTarget("type")
	@XMLSimple("type")
	private java.lang.String type;
	
	public java.lang.String getType() {
		return type;
	}
	
	public DBSettlementTypesBean setType(java.lang.String value) {
		this.type = value;
		return this;
	}
	
	
	@DataSource({"title", "title"})
	@DataTarget("title")
	@XMLSimple("title")
	private java.lang.String title;
	
	public java.lang.String getTitle() {
		return title;
	}
	
	public DBSettlementTypesBean setTitle(java.lang.String value) {
		this.title = value;
		return this;
	}
	
	
	@DataSource({"group", "group"})
	@DataTarget("group")
	@XMLSimple("group")
	private String group;
	
	public String getGroup() {
		return group;
	}
	
	public DBSettlementTypesBean setGroup(String value) {
		this.group = value;
		return this;
	}
	
	@Override
	public void setAutoincrementField(Object value) {
		
		setSettlementTypeId(new java.lang.Long(value.toString()));
		
	}	
	
}