/**
 *  Autogenerated class
 */
package org.c3s.edgo.common.beans;

import java.io.Serializable;
import java.util.*;
import org.c3s.db.beans.DbBean;
import org.c3s.data.annotations.DataSource;
import org.c3s.data.annotations.DataTarget;
import org.c3s.reflection.annotation.*;


public class DBSettlementsSearchBean implements DbBean, Serializable {

	private static final long serialVersionUID = 1L;


	
	@DataSource({"settlement_type_id", "settlementTypeId"})
	@DataTarget("settlement_type_id")
	@XMLSimple("settlementTypeId")
	private java.lang.Long settlementTypeId;
	
	public java.lang.Long getSettlementTypeId() {
		return settlementTypeId;
	}
	
	public DBSettlementsSearchBean setSettlementTypeId(java.lang.Long value) {
		this.settlementTypeId = value;
		return this;
	}
	
	
	@DataSource({"settlement_id", "settlementId"})
	@DataTarget("settlement_id")
	@XMLSimple("settlementId")
	private java.lang.Long settlementId;
	
	public java.lang.Long getSettlementId() {
		return settlementId;
	}
	
	public DBSettlementsSearchBean setSettlementId(java.lang.Long value) {
		this.settlementId = value;
		return this;
	}
	
	
	@DataSource({"system_id", "systemId"})
	@DataTarget("system_id")
	@XMLSimple("systemId")
	private java.math.BigInteger systemId;
	
	public java.math.BigInteger getSystemId() {
		return systemId;
	}
	
	public DBSettlementsSearchBean setSystemId(java.math.BigInteger value) {
		this.systemId = value;
		return this;
	}
	
	
	@DataSource({"planet", "planet"})
	@DataTarget("planet")
	@XMLSimple("planet")
	private java.lang.String planet;
	
	public java.lang.String getPlanet() {
		return planet;
	}
	
	public DBSettlementsSearchBean setPlanet(java.lang.String value) {
		this.planet = value;
		return this;
	}
	
	
	@DataSource({"system_name", "systemName"})
	@DataTarget("name")
	@XMLSimple("systemName")
	private java.lang.String systemName;
	
	public java.lang.String getSystemName() {
		return systemName;
	}
	
	public DBSettlementsSearchBean setSystemName(java.lang.String value) {
		this.systemName = value;
		return this;
	}
	
	
	@DataSource({"name", "name"})
	@DataTarget("name")
	@XMLSimple("name")
	private java.lang.String name;
	
	public java.lang.String getName() {
		return name;
	}
	
	public DBSettlementsSearchBean setName(java.lang.String value) {
		this.name = value;
		return this;
	}
	
	
	@DataSource({"x", "x"})
	@DataTarget("x")
	@XMLSimple("x")
	private java.lang.Double x;
	
	public java.lang.Double getX() {
		return x;
	}
	
	public DBSettlementsSearchBean setX(java.lang.Double value) {
		this.x = value;
		return this;
	}
	
	
	@DataSource({"y", "y"})
	@DataTarget("y")
	@XMLSimple("y")
	private java.lang.Double y;
	
	public java.lang.Double getY() {
		return y;
	}
	
	public DBSettlementsSearchBean setY(java.lang.Double value) {
		this.y = value;
		return this;
	}
	
	
	@DataSource({"z", "z"})
	@DataTarget("z")
	@XMLSimple("z")
	private java.lang.Double z;
	
	public java.lang.Double getZ() {
		return z;
	}
	
	public DBSettlementsSearchBean setZ(java.lang.Double value) {
		this.z = value;
		return this;
	}
	
	
	@DataSource({"title", "title"})
	@DataTarget("title")
	@XMLSimple("title")
	private java.lang.String title;
	
	public java.lang.String getTitle() {
		return title;
	}
	
	public DBSettlementsSearchBean setTitle(java.lang.String value) {
		this.title = value;
		return this;
	}
	
	
	@DataSource({"dest", "dest"})
	@DataTarget("dest")
	@XMLSimple("dest")

	private Double dest;
	
	public Double getDest() {
		return dest;
	}
	
	public DBSettlementsSearchBean setDest(Double value) {
		this.dest = value;
		return this;
	}
	
	
	@DataSource({"sol_dest", "solDest"})
	@DataTarget("sol_dest")
	@XMLSimple("solDest")

	private Double solDest;
	
	public Double getSolDest() {
		return solDest;
	}
	
	public DBSettlementsSearchBean setSolDest(Double value) {
		this.solDest = value;
		return this;
	}
	
	@Override
	public void setAutoincrementField(Object value) {
		
		setSettlementId(new java.lang.Long(value.toString()));
		
	}	
	
}