/**
 *  Autogenerated class
 */
package org.c3s.edgo.common.beans;

import java.io.Serializable;
import java.util.*;
import org.c3s.db.beans.DbBean;
import org.c3s.data.annotations.DataSource;
import org.c3s.data.annotations.DataTarget;
import org.c3s.reflection.annotation.*;


public class DBSlotsBean implements DbBean, Serializable {

	private static final long serialVersionUID = 1L;


	
	@DataSource({"size", "size"})
	@DataTarget("size")
	@XMLSimple("size")
	private java.lang.Integer size;
	
	public java.lang.Integer getSize() {
		return size;
	}
	
	public DBSlotsBean setSize(java.lang.Integer value) {
		size = value;
		return this;
	}
	
	
	@DataSource({"slot_id", "slotId"})
	@DataTarget("slot_id")
	@XMLSimple("slotId")
	private java.lang.Long slotId;
	
	public java.lang.Long getSlotId() {
		return slotId;
	}
	
	public DBSlotsBean setSlotId(java.lang.Long value) {
		slotId = value;
		return this;
	}
	
	
	@DataSource({"slot_uniq", "slotUniq"})
	@DataTarget("slot_uniq")
	@XMLSimple("slotUniq")
	private java.lang.String slotUniq;
	
	public java.lang.String getSlotUniq() {
		return slotUniq;
	}
	
	public DBSlotsBean setSlotUniq(java.lang.String value) {
		slotUniq = value;
		return this;
	}
	
	
	@DataSource({"slot_type_id", "slotTypeId"})
	@DataTarget("slot_type_id")
	@XMLSimple("slotTypeId")
	private java.lang.Long slotTypeId;
	
	public java.lang.Long getSlotTypeId() {
		return slotTypeId;
	}
	
	public DBSlotsBean setSlotTypeId(java.lang.Long value) {
		slotTypeId = value;
		return this;
	}
	
	@Override
	public void setAutoincrementField(Object value) {
		
		setSlotId(new java.lang.Long(value.toString()));
		
	}	
	
}