/**
 *  Autogenerated class
 */
package org.c3s.edgo.common.beans;

import java.io.Serializable;
import java.util.*;
import org.c3s.db.beans.DbBean;
import org.c3s.data.annotations.DataSource;
import org.c3s.data.annotations.DataTarget;
import org.c3s.reflection.annotation.*;


public class DBStationsBean implements DbBean, Serializable {

	private static final long serialVersionUID = 1L;


	
	@DataSource({"settlement_security", "settlementSecurity"})
	@DataTarget("settlement_security")
	@XMLSimple("settlementSecurity")
	private java.lang.String settlementSecurity;
	
	public java.lang.String getSettlementSecurity() {
		return settlementSecurity;
	}
	
	public DBStationsBean setSettlementSecurity(java.lang.String value) {
		this.settlementSecurity = value;
		return this;
	}
	
	
	@DataSource({"faction_id", "factionId"})
	@DataTarget("faction_id")
	@XMLSimple("factionId")
	private java.lang.Long factionId;
	
	public java.lang.Long getFactionId() {
		return factionId;
	}
	
	public DBStationsBean setFactionId(java.lang.Long value) {
		this.factionId = value;
		return this;
	}
	
	
	@DataSource({"settlement_security_id", "settlementSecurityId"})
	@DataTarget("settlement_security_id")
	@XMLSimple("settlementSecurityId")
	private java.lang.Long settlementSecurityId;
	
	public java.lang.Long getSettlementSecurityId() {
		return settlementSecurityId;
	}
	
	public DBStationsBean setSettlementSecurityId(java.lang.Long value) {
		this.settlementSecurityId = value;
		return this;
	}
	
	
	@DataSource({"type", "type"})
	@DataTarget("type")
	@XMLSimple("type")
	private java.lang.String type;
	
	public java.lang.String getType() {
		return type;
	}
	
	public DBStationsBean setType(java.lang.String value) {
		this.type = value;
		return this;
	}
	
	
	@DataSource({"has_refuel", "hasRefuel"})
	@DataTarget("has_refuel")
	@XMLSimple("hasRefuel")
	private java.lang.Integer hasRefuel;
	
	public java.lang.Integer getHasRefuel() {
		return hasRefuel;
	}
	
	public DBStationsBean setHasRefuel(java.lang.Integer value) {
		this.hasRefuel = value;
		return this;
	}
	
	
	@DataSource({"has_shipyard", "hasShipyard"})
	@DataTarget("has_shipyard")
	@XMLSimple("hasShipyard")
	private java.lang.Integer hasShipyard;
	
	public java.lang.Integer getHasShipyard() {
		return hasShipyard;
	}
	
	public DBStationsBean setHasShipyard(java.lang.Integer value) {
		this.hasShipyard = value;
		return this;
	}
	
	
	@DataSource({"has_blackmarket", "hasBlackmarket"})
	@DataTarget("has_blackmarket")
	@XMLSimple("hasBlackmarket")
	private java.lang.Integer hasBlackmarket;
	
	public java.lang.Integer getHasBlackmarket() {
		return hasBlackmarket;
	}
	
	public DBStationsBean setHasBlackmarket(java.lang.Integer value) {
		this.hasBlackmarket = value;
		return this;
	}
	
	
	@DataSource({"has_commodities", "hasCommodities"})
	@DataTarget("has_commodities")
	@XMLSimple("hasCommodities")
	private java.lang.Integer hasCommodities;
	
	public java.lang.Integer getHasCommodities() {
		return hasCommodities;
	}
	
	public DBStationsBean setHasCommodities(java.lang.Integer value) {
		this.hasCommodities = value;
		return this;
	}
	
	
	@DataSource({"settlement_size_id", "settlementSizeId"})
	@DataTarget("settlement_size_id")
	@XMLSimple("settlementSizeId")
	private java.lang.Long settlementSizeId;
	
	public java.lang.Long getSettlementSizeId() {
		return settlementSizeId;
	}
	
	public DBStationsBean setSettlementSizeId(java.lang.Long value) {
		this.settlementSizeId = value;
		return this;
	}
	
	
	@DataSource({"government", "government"})
	@DataTarget("government")
	@XMLSimple("government")
	private java.lang.String government;
	
	public java.lang.String getGovernment() {
		return government;
	}
	
	public DBStationsBean setGovernment(java.lang.String value) {
		this.government = value;
		return this;
	}
	
	
	@DataSource({"updated_at", "updatedAt"})
	@DataTarget("updated_at")
	@XMLSimple("updatedAt")
	private java.lang.Long updatedAt;
	
	public java.lang.Long getUpdatedAt() {
		return updatedAt;
	}
	
	public DBStationsBean setUpdatedAt(java.lang.Long value) {
		this.updatedAt = value;
		return this;
	}
	
	
	@DataSource({"state", "state"})
	@DataTarget("state")
	@XMLSimple("state")
	private java.lang.String state;
	
	public java.lang.String getState() {
		return state;
	}
	
	public DBStationsBean setState(java.lang.String value) {
		this.state = value;
		return this;
	}
	
	
	@DataSource({"body_id", "bodyId"})
	@DataTarget("body_id")
	@XMLSimple("bodyId")
	private java.lang.Long bodyId;
	
	public java.lang.Long getBodyId() {
		return bodyId;
	}
	
	public DBStationsBean setBodyId(java.lang.Long value) {
		this.bodyId = value;
		return this;
	}
	
	
	@DataSource({"has_docking", "hasDocking"})
	@DataTarget("has_docking")
	@XMLSimple("hasDocking")
	private java.lang.Integer hasDocking;
	
	public java.lang.Integer getHasDocking() {
		return hasDocking;
	}
	
	public DBStationsBean setHasDocking(java.lang.Integer value) {
		this.hasDocking = value;
		return this;
	}
	
	
	@DataSource({"max_landing_pad_size", "maxLandingPadSize"})
	@DataTarget("max_landing_pad_size")
	@XMLSimple("maxLandingPadSize")
	private java.lang.String maxLandingPadSize;
	
	public java.lang.String getMaxLandingPadSize() {
		return maxLandingPadSize;
	}
	
	public DBStationsBean setMaxLandingPadSize(java.lang.String value) {
		this.maxLandingPadSize = value;
		return this;
	}
	
	
	@DataSource({"has_outfitting", "hasOutfitting"})
	@DataTarget("has_outfitting")
	@XMLSimple("hasOutfitting")
	private java.lang.Integer hasOutfitting;
	
	public java.lang.Integer getHasOutfitting() {
		return hasOutfitting;
	}
	
	public DBStationsBean setHasOutfitting(java.lang.Integer value) {
		this.hasOutfitting = value;
		return this;
	}
	
	
	@DataSource({"system_id", "systemId"})
	@DataTarget("system_id")
	@XMLSimple("systemId")
	private java.math.BigInteger systemId;
	
	public java.math.BigInteger getSystemId() {
		return systemId;
	}
	
	public DBStationsBean setSystemId(java.math.BigInteger value) {
		this.systemId = value;
		return this;
	}
	
	
	@DataSource({"type_id", "typeId"})
	@DataTarget("type_id")
	@XMLSimple("typeId")
	private java.lang.Long typeId;
	
	public java.lang.Long getTypeId() {
		return typeId;
	}
	
	public DBStationsBean setTypeId(java.lang.Long value) {
		this.typeId = value;
		return this;
	}
	
	
	@DataSource({"has_market", "hasMarket"})
	@DataTarget("has_market")
	@XMLSimple("hasMarket")
	private java.lang.Integer hasMarket;
	
	public java.lang.Integer getHasMarket() {
		return hasMarket;
	}
	
	public DBStationsBean setHasMarket(java.lang.Integer value) {
		this.hasMarket = value;
		return this;
	}
	
	
	@DataSource({"station_id", "stationId"})
	@DataTarget("station_id")
	@XMLSimple("stationId")
	private java.lang.Long stationId;
	
	public java.lang.Long getStationId() {
		return stationId;
	}
	
	public DBStationsBean setStationId(java.lang.Long value) {
		this.stationId = value;
		return this;
	}
	
	
	@DataSource({"market_id", "marketId"})
	@DataTarget("market_id")
	@XMLSimple("marketId")
	private java.math.BigInteger marketId;
	
	public java.math.BigInteger getMarketId() {
		return marketId;
	}
	
	public DBStationsBean setMarketId(java.math.BigInteger value) {
		this.marketId = value;
		return this;
	}
	
	
	@DataSource({"allegiance", "allegiance"})
	@DataTarget("allegiance")
	@XMLSimple("allegiance")
	private java.lang.String allegiance;
	
	public java.lang.String getAllegiance() {
		return allegiance;
	}
	
	public DBStationsBean setAllegiance(java.lang.String value) {
		this.allegiance = value;
		return this;
	}
	
	
	@DataSource({"economies", "economies"})
	@DataTarget("economies")
	@XMLSimple("economies")
	private java.lang.String economies;
	
	public java.lang.String getEconomies() {
		return economies;
	}
	
	public DBStationsBean setEconomies(java.lang.String value) {
		this.economies = value;
		return this;
	}
	
	
	@DataSource({"has_repair", "hasRepair"})
	@DataTarget("has_repair")
	@XMLSimple("hasRepair")
	private java.lang.Integer hasRepair;
	
	public java.lang.Integer getHasRepair() {
		return hasRepair;
	}
	
	public DBStationsBean setHasRepair(java.lang.Integer value) {
		this.hasRepair = value;
		return this;
	}
	
	
	@DataSource({"name", "name"})
	@DataTarget("name")
	@XMLSimple("name")
	private java.lang.String name;
	
	public java.lang.String getName() {
		return name;
	}
	
	public DBStationsBean setName(java.lang.String value) {
		this.name = value;
		return this;
	}
	
	
	@DataSource({"has_rearm", "hasRearm"})
	@DataTarget("has_rearm")
	@XMLSimple("hasRearm")
	private java.lang.Integer hasRearm;
	
	public java.lang.Integer getHasRearm() {
		return hasRearm;
	}
	
	public DBStationsBean setHasRearm(java.lang.Integer value) {
		this.hasRearm = value;
		return this;
	}
	
	
	@DataSource({"settlement_size", "settlementSize"})
	@DataTarget("settlement_size")
	@XMLSimple("settlementSize")
	private java.lang.String settlementSize;
	
	public java.lang.String getSettlementSize() {
		return settlementSize;
	}
	
	public DBStationsBean setSettlementSize(java.lang.String value) {
		this.settlementSize = value;
		return this;
	}
	
	
	@DataSource({"is_planetary", "isPlanetary"})
	@DataTarget("is_planetary")
	@XMLSimple("isPlanetary")
	private java.lang.Integer isPlanetary;
	
	public java.lang.Integer getIsPlanetary() {
		return isPlanetary;
	}
	
	public DBStationsBean setIsPlanetary(java.lang.Integer value) {
		this.isPlanetary = value;
		return this;
	}
	
	
	@DataSource({"distance_to_star", "distanceToStar"})
	@DataTarget("distance_to_star")
	@XMLSimple("distanceToStar")
	private java.lang.Long distanceToStar;
	
	public java.lang.Long getDistanceToStar() {
		return distanceToStar;
	}
	
	public DBStationsBean setDistanceToStar(java.lang.Long value) {
		this.distanceToStar = value;
		return this;
	}
	
	
	@DataSource({"name_uniq", "nameUniq"})
	@DataTarget("name_uniq")
	@XMLSimple("nameUniq")
	private java.lang.String nameUniq;
	
	public java.lang.String getNameUniq() {
		return nameUniq;
	}
	
	public DBStationsBean setNameUniq(java.lang.String value) {
		this.nameUniq = value;
		return this;
	}
	
	@Override
	public void setAutoincrementField(Object value) {
		
	}	
	
}