/**
 *  Autogenerated class
 */
package org.c3s.edgo.common.beans;

import java.io.Serializable;
import java.util.*;
import org.c3s.db.beans.DbBean;
import org.c3s.data.annotations.DataSource;
import org.c3s.data.annotations.DataTarget;
import org.c3s.reflection.annotation.*;


public class DBSystemFactionPendingStatesBean implements DbBean, Serializable {

	private static final long serialVersionUID = 1L;


	
	@DataSource({"trend", "trend"})
	@DataTarget("trend")
	@XMLSimple("trend")
	private java.lang.Integer trend;
	
	public java.lang.Integer getTrend() {
		return trend;
	}
	
	public DBSystemFactionPendingStatesBean setTrend(java.lang.Integer value) {
		this.trend = value;
		return this;
	}
	
	
	@DataSource({"state_id", "stateId"})
	@DataTarget("state_id")
	@XMLSimple("stateId")
	private java.lang.Long stateId;
	
	public java.lang.Long getStateId() {
		return stateId;
	}
	
	public DBSystemFactionPendingStatesBean setStateId(java.lang.Long value) {
		this.stateId = value;
		return this;
	}
	
	
	@DataSource({"system_factions_history_id", "systemFactionsHistoryId"})
	@DataTarget("system_factions_history_id")
	@XMLSimple("systemFactionsHistoryId")
	private java.math.BigInteger systemFactionsHistoryId;
	
	public java.math.BigInteger getSystemFactionsHistoryId() {
		return systemFactionsHistoryId;
	}
	
	public DBSystemFactionPendingStatesBean setSystemFactionsHistoryId(java.math.BigInteger value) {
		this.systemFactionsHistoryId = value;
		return this;
	}
	
	@Override
	public void setAutoincrementField(Object value) {
		
	}	
	
}