/**
 *  Autogenerated class
 */
package org.c3s.edgo.common.beans;

import java.io.Serializable;
import java.util.*;
import org.c3s.db.beans.DbBean;
import org.c3s.data.annotations.DataSource;
import org.c3s.data.annotations.DataTarget;
import org.c3s.reflection.annotation.*;


public class DBTumbnailsForImageBean implements DbBean, Serializable {

	private static final long serialVersionUID = 1L;


	
	@DataSource({"config_name", "configName"})
	@DataTarget("config_name")
	@XMLSimple("configName")
	private java.lang.String configName;
	
	public java.lang.String getConfigName() {
		return configName;
	}
	
	public DBTumbnailsForImageBean setConfigName(java.lang.String value) {
		configName = value;
		return this;
	}
	
	
	@DataSource({"update_time", "updateTime"})
	@DataTarget("update_time")
	@XMLSimple("updateTime")
	private java.sql.Timestamp updateTime;
	
	public java.sql.Timestamp getUpdateTime() {
		return updateTime;
	}
	
	public DBTumbnailsForImageBean setUpdateTime(java.sql.Timestamp value) {
		updateTime = value;
		return this;
	}
	
	
	@DataSource({"create_time", "createTime"})
	@DataTarget("create_time")
	@XMLSimple("createTime")
	private java.sql.Timestamp createTime;
	
	public java.sql.Timestamp getCreateTime() {
		return createTime;
	}
	
	public DBTumbnailsForImageBean setCreateTime(java.sql.Timestamp value) {
		createTime = value;
		return this;
	}
	
	
	@DataSource({"config_id", "configId"})
	@DataTarget("config_id")
	@XMLSimple("configId")
	private java.lang.Long configId;
	
	public java.lang.Long getConfigId() {
		return configId;
	}
	
	public DBTumbnailsForImageBean setConfigId(java.lang.Long value) {
		configId = value;
		return this;
	}
	
	
	@DataSource({"width", "width"})
	@DataTarget("width")
	@XMLSimple("width")
	private java.lang.Long width;
	
	public java.lang.Long getWidth() {
		return width;
	}
	
	public DBTumbnailsForImageBean setWidth(java.lang.Long value) {
		width = value;
		return this;
	}
	
	
	@DataSource({"tumbnail_id", "tumbnailId"})
	@DataTarget("tumbnail_id")
	@XMLSimple("tumbnailId")
	private java.lang.Long tumbnailId;
	
	public java.lang.Long getTumbnailId() {
		return tumbnailId;
	}
	
	public DBTumbnailsForImageBean setTumbnailId(java.lang.Long value) {
		tumbnailId = value;
		return this;
	}
	
	
	@DataSource({"image_id", "imageId"})
	@DataTarget("image_id")
	@XMLSimple("imageId")
	private java.lang.Long imageId;
	
	public java.lang.Long getImageId() {
		return imageId;
	}
	
	public DBTumbnailsForImageBean setImageId(java.lang.Long value) {
		imageId = value;
		return this;
	}
	
	
	@DataSource({"type", "type"})
	@DataTarget("type")
	@XMLSimple("type")
	private java.lang.String type;
	
	public java.lang.String getType() {
		return type;
	}
	
	public DBTumbnailsForImageBean setType(java.lang.String value) {
		type = value;
		return this;
	}
	
	
	@DataSource({"height", "height"})
	@DataTarget("height")
	@XMLSimple("height")
	private java.lang.Long height;
	
	public java.lang.Long getHeight() {
		return height;
	}
	
	public DBTumbnailsForImageBean setHeight(java.lang.Long value) {
		height = value;
		return this;
	}
	
	@Override
	public void setAutoincrementField(Object value) {
		
		setTumbnailId(new java.lang.Long(value.toString()));
		
	}	
	
}