/**
 *  Autogenerated class
 */
package org.c3s.edgo.common.beans;

import java.io.Serializable;
import java.util.*;
import org.c3s.db.beans.DbBean;
import org.c3s.data.annotations.DataSource;
import org.c3s.data.annotations.DataTarget;
import org.c3s.reflection.annotation.*;


public class DBUserInfoWithDefaultsBean implements DbBean, Serializable {

	private static final long serialVersionUID = 1L;


	
	@DataSource({"def_level", "defLevel"})
	@DataTarget("def_level")
	@XMLSimple("defLevel")
	private java.lang.Long defLevel;
	
	public java.lang.Long getDefLevel() {
		return defLevel;
	}
	
	public DBUserInfoWithDefaultsBean setDefLevel(java.lang.Long value) {
		defLevel = value;
		return this;
	}
	
	
	@DataSource({"level", "level"})
	@DataTarget("level")
	@XMLSimple("level")
	private java.lang.Long level;
	
	public java.lang.Long getLevel() {
		return level;
	}
	
	public DBUserInfoWithDefaultsBean setLevel(java.lang.Long value) {
		level = value;
		return this;
	}
	
	
	@DataSource({"info_id", "infoId"})
	@DataTarget("info_id")
	@XMLSimple("infoId")
	private java.lang.Long infoId;
	
	public java.lang.Long getInfoId() {
		return infoId;
	}
	
	public DBUserInfoWithDefaultsBean setInfoId(java.lang.Long value) {
		infoId = value;
		return this;
	}
	
	
	@DataSource({"info_uniq", "infoUniq"})
	@DataTarget("info_uniq")
	@XMLSimple("infoUniq")
	private java.lang.String infoUniq;
	
	public java.lang.String getInfoUniq() {
		return infoUniq;
	}
	
	public DBUserInfoWithDefaultsBean setInfoUniq(java.lang.String value) {
		infoUniq = value;
		return this;
	}
	
	
	@DataSource({"sort", "sort"})
	@DataTarget("sort")
	@XMLSimple("sort")
	private java.lang.Long sort;
	
	public java.lang.Long getSort() {
		return sort;
	}
	
	public DBUserInfoWithDefaultsBean setSort(java.lang.Long value) {
		sort = value;
		return this;
	}
	
	
	@DataSource({"info_link", "infoLink"})
	@DataTarget("info_link")
	@XMLSimple("infoLink")
	private java.lang.String infoLink;
	
	public java.lang.String getInfoLink() {
		return infoLink;
	}
	
	public DBUserInfoWithDefaultsBean setInfoLink(java.lang.String value) {
		infoLink = value;
		return this;
	}
	
	@Override
	public void setAutoincrementField(Object value) {
		
		setInfoId(new java.lang.Long(value.toString()));
		
	}	
	
}