/**
 *  Autogenerated class
 */
package org.c3s.edgo.common.beans;

import java.io.Serializable;
import java.util.*;
import org.c3s.db.beans.DbBean;
import org.c3s.data.annotations.DataSource;
import org.c3s.data.annotations.DataTarget;
import org.c3s.reflection.annotation.*;


public class DBUserKeysBean implements DbBean, Serializable {

	private static final long serialVersionUID = 1L;


	
	@DataSource({"public_key", "publicKey"})
	@DataTarget("public_key")
	@XMLSimple("publicKey")
	private java.lang.String publicKey;
	
	public java.lang.String getPublicKey() {
		return publicKey;
	}
	
	public DBUserKeysBean setPublicKey(java.lang.String value) {
		this.publicKey = value;
		return this;
	}
	
	
	@DataSource({"update_time", "updateTime"})
	@DataTarget("update_time")
	@XMLSimple("updateTime")
	private java.sql.Timestamp updateTime;
	
	public java.sql.Timestamp getUpdateTime() {
		return updateTime;
	}
	
	public DBUserKeysBean setUpdateTime(java.sql.Timestamp value) {
		this.updateTime = value;
		return this;
	}
	
	
	@DataSource({"create_time", "createTime"})
	@DataTarget("create_time")
	@XMLSimple("createTime")
	private java.sql.Timestamp createTime;
	
	public java.sql.Timestamp getCreateTime() {
		return createTime;
	}
	
	public DBUserKeysBean setCreateTime(java.sql.Timestamp value) {
		this.createTime = value;
		return this;
	}
	
	
	@DataSource({"user_key_id", "userKeyId"})
	@DataTarget("user_key_id")
	@XMLSimple("userKeyId")
	private java.lang.Long userKeyId;
	
	public java.lang.Long getUserKeyId() {
		return userKeyId;
	}
	
	public DBUserKeysBean setUserKeyId(java.lang.Long value) {
		this.userKeyId = value;
		return this;
	}
	
	
	@DataSource({"session_key", "sessionKey"})
	@DataTarget("session_key")
	@XMLSimple("sessionKey")
	private java.lang.String sessionKey;
	
	public java.lang.String getSessionKey() {
		return sessionKey;
	}
	
	public DBUserKeysBean setSessionKey(java.lang.String value) {
		this.sessionKey = value;
		return this;
	}
	
	
	@DataSource({"private_key", "privateKey"})
	@DataTarget("private_key")
	@XMLSimple("privateKey")
	private java.lang.String privateKey;
	
	public java.lang.String getPrivateKey() {
		return privateKey;
	}
	
	public DBUserKeysBean setPrivateKey(java.lang.String value) {
		this.privateKey = value;
		return this;
	}
	
	@Override
	public void setAutoincrementField(Object value) {
		
		setUserKeyId(new java.lang.Long(value.toString()));
		
	}	
	
}