/**
 *  Autogenerated class
 */
package org.c3s.edgo.common.access;

import java.sql.SQLException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import org.c3s.db.access.Access;
import org.c3s.db.*;
import org.c3s.db.beans.*;
import org.c3s.db.injectors.SqlInjectorInterface;
import org.c3s.db.injectors.EmptySqlInjector;
import org.c3s.data.mapers.*;
import org.c3s.data.cast.*;


import org.c3s.edgo.common.beans.*;


@SuppressWarnings("unused")
public class DBEngEngeneersGradeAccess extends Access {
	protected DBConnection getConnection() {
		setNames();
		return getCon();
	}
	
	private DataMapper dataMapper = new GeneralDataMapper(new GeneralCastType()); 
	
	protected void setNames() {
		con_name = "edgo";
		tablename = "eng_engeneers_grade";
	}
	
	
	public int insert(DBEngEngeneersGradeBean bean) throws SQLException, IllegalArgumentException, IllegalAccessException {
		setNames();
		int res = _insert(bean);
		bean.setAutoincrementField(res);
		return res;
	}

	
	public List<DBEngEngeneersGradeBean> getTableRecords() throws SQLException, IllegalArgumentException, IllegalAccessException, InstantiationException {
		return getTableRecords(null);
	}
	public List<DBEngEngeneersGradeBean> getTableRecords(SqlInjectorInterface injector) throws SQLException, IllegalArgumentException, IllegalAccessException, InstantiationException {
		setNames();
		List<Map<String, Object>> result = _getTableRecords(injector);
		
		List<DBEngEngeneersGradeBean> ret = null;
		if (result != null) {
			ret = new ArrayList<DBEngEngeneersGradeBean>();
			for (Map<String, Object> res : result) {
				DBEngEngeneersGradeBean bean = dataMapper.mapFromRow(res, DBEngEngeneersGradeBean.class);
				
				ret.add(bean);
			}
		}
		return ret;
	}
	
	
	public List<DBEngeneersForBlueprintsBean> getEngeneersForBlueprints() throws SQLException, IllegalArgumentException, IllegalAccessException, InstantiationException {
		setNames();
		SqlInjectorInterface injector = new EmptySqlInjector();
		
		
		String query = injector.getFullQuery();
		if (query == null) {
			String record = injector.getRecordQuery();
			String from = injector.getFromQuery();
			String join = injector.getJoinQuery();
			String where = injector.getWhereQuery();
			String order = injector.getOrderQuery();
			String limit = injector.getLimitQuery();
			query = " 				SELECT eg.eng_grade_id, GROUP_CONCAT(e.engeneer_name ORDER BY e.engeneer_name SEPARATOR ', ') as engeneers 				FROM eng_engeneers_grade eg 				LEFT JOIN eng_engeneers e ON e.eng_engeneer_id = eg.eng_engeneer_id 				GROUP BY eg.eng_grade_id 				ORDER BY eg.eng_grade_id 			";
		}

		
		List<Map<String, Object>> result = getConnection().fetchRows(tablename + ".getEngeneersForBlueprints", query );
		List<DBEngeneersForBlueprintsBean> ret = null;
		if (result != null) {
					ret = new ArrayList<DBEngeneersForBlueprintsBean>();
				
			for (Map<String, Object> res : result) {
				DBEngeneersForBlueprintsBean bean = dataMapper.mapFromRow(res, DBEngeneersForBlueprintsBean.class);
														
				ret.add(bean);
			}
					
		}
			
		return ret;
	}
	
}