/**
 *  Autogenerated class
 */
package org.c3s.edgo.common.access;

import java.sql.SQLException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import org.c3s.db.access.Access;
import org.c3s.db.*;
import org.c3s.db.beans.*;
import org.c3s.db.injectors.SqlInjectorInterface;
import org.c3s.db.injectors.EmptySqlInjector;
import org.c3s.data.mapers.*;
import org.c3s.data.cast.*;
import org.c3s.edgo.utils.cast.EdGoCast;


import org.c3s.edgo.common.beans.*;


@SuppressWarnings("unused")
public class DBEngBlueprintAccess extends Access {
	protected DBConnection getConnection() {
		setNames();
		return getCon();
	}
	
	private DataMapper dataMapper = new GeneralDataMapper(new EdGoCast()); 
	
	protected void setNames() {
		con_name = "edgo";
		tablename = "eng_blueprint";
	}
	
	
	public int insert(DBEngBlueprintBean bean) throws SQLException, IllegalArgumentException, IllegalAccessException {
		setNames();
		int res = _insert(bean);
		bean.setAutoincrementField(res);
		return res;
	}

	
	public List<DBEngBlueprintBean> getTableRecords() throws SQLException, IllegalArgumentException, IllegalAccessException, InstantiationException {
		return getTableRecords(null);
	}
	public List<DBEngBlueprintBean> getTableRecords(SqlInjectorInterface injector) throws SQLException, IllegalArgumentException, IllegalAccessException, InstantiationException {
		setNames();
		List<Map<String, Object>> result = _getTableRecords(injector);
		
		List<DBEngBlueprintBean> ret = null;
		if (result != null) {
			ret = new ArrayList<DBEngBlueprintBean>();
			for (Map<String, Object> res : result) {
				DBEngBlueprintBean bean = dataMapper.mapFromRow(res, DBEngBlueprintBean.class);
				
				ret.add(bean);
			}
		}
		return ret;
	}
	
	
	public List<DBEngBlueprintBean> getOrderedByTypeId(java.lang.Long paramEngTypeId)  throws SQLException, IllegalArgumentException, IllegalAccessException, InstantiationException {
		setNames();
		List<DBEngBlueprintBean> ret = null;
		SqlInjectorInterface injector = new EmptySqlInjector();
		
		String sql = "SELECT t.* "+injector.getRecordQuery()+" FROM " + tablename + " as t "+injector.getFromQuery()+" WHERE 1=1  AND  eng_type_id= ?  "+injector.getWhereQuery()+" ";
		if (injector.getOrderQuery().length() != 0) {
			sql += injector.getOrderQuery();
		} else { 
			sql += "ORDER BY eng_blueprint_uniq";
			
		}
		String limit = injector.getLimitQuery();
		if (limit.length() != 0) {
			sql += limit;
		} else {
			
		}
		
		
		
		
		List<Map<String, Object>> result = getConnection().fetchRows(tablename + ".getOrderedByTypeId", sql ,  paramEngTypeId);
		if (result != null) {
			
			ret = new ArrayList<DBEngBlueprintBean>();
			for (Map<String, Object> res : result) {
				DBEngBlueprintBean bean = dataMapper.mapFromRow(res, DBEngBlueprintBean.class);
				 
				ret.add(bean);
			}
				
		}
		return ret;
	}
	
	public List<DBEngBlueprintBean> getOrdered()  throws SQLException, IllegalArgumentException, IllegalAccessException, InstantiationException {
		setNames();
		List<DBEngBlueprintBean> ret = null;
		SqlInjectorInterface injector = new EmptySqlInjector();
		
		String sql = "SELECT t.* "+injector.getRecordQuery()+" FROM " + tablename + " as t "+injector.getFromQuery()+" WHERE 1=1  "+injector.getWhereQuery()+" ";
		if (injector.getOrderQuery().length() != 0) {
			sql += injector.getOrderQuery();
		} else { 
			sql += "ORDER BY eng_blueprint_uniq";
			
		}
		String limit = injector.getLimitQuery();
		if (limit.length() != 0) {
			sql += limit;
		} else {
			
		}
		
		
		
		
		List<Map<String, Object>> result = getConnection().fetchRows(tablename + ".getOrdered", sql );
		if (result != null) {
			
			ret = new ArrayList<DBEngBlueprintBean>();
			for (Map<String, Object> res : result) {
				DBEngBlueprintBean bean = dataMapper.mapFromRow(res, DBEngBlueprintBean.class);
				 
				ret.add(bean);
			}
				
		}
		return ret;
	}
	
	public DBEngBlueprintBean getByUniq(java.lang.String paramEngBlueprintUniq)  throws SQLException, IllegalArgumentException, IllegalAccessException, InstantiationException {
		setNames();
		DBEngBlueprintBean ret = null;
		SqlInjectorInterface injector = new EmptySqlInjector();
		
		String sql = "SELECT t.* "+injector.getRecordQuery()+" FROM " + tablename + " as t "+injector.getFromQuery()+" WHERE 1=1  AND  eng_blueprint_uniq= ?  "+injector.getWhereQuery()+" ";
		if (injector.getOrderQuery().length() != 0) {
			sql += injector.getOrderQuery();
		} else { 
			
		}
		String limit = injector.getLimitQuery();
		if (limit.length() != 0) {
			sql += limit;
		} else {
			sql += " LIMIT 1";
		}
		
		
		
		
		List<Map<String, Object>> result = getConnection().fetchRows(tablename + ".getByUniq", sql ,  paramEngBlueprintUniq);
		if (result != null) {
			
			ret = dataMapper.mapFromRow(result.get(0), DBEngBlueprintBean.class);
			
		}
		return ret;
	}
	
	public DBEngBlueprintBean getByPrimaryKey(java.lang.Long paramEngBlueprintId)  throws SQLException, IllegalArgumentException, IllegalAccessException, InstantiationException {
		setNames();
		DBEngBlueprintBean ret = null;
		SqlInjectorInterface injector = new EmptySqlInjector();
		
		String sql = "SELECT t.* "+injector.getRecordQuery()+" FROM " + tablename + " as t "+injector.getFromQuery()+" WHERE 1=1  AND  eng_blueprint_id= ?  "+injector.getWhereQuery()+" ";
		if (injector.getOrderQuery().length() != 0) {
			sql += injector.getOrderQuery();
		} else { 
			
		}
		String limit = injector.getLimitQuery();
		if (limit.length() != 0) {
			sql += limit;
		} else {
			sql += " LIMIT 1";
		}
		
		
		
		
		List<Map<String, Object>> result = getConnection().fetchRows(tablename + ".getByPrimaryKey", sql ,  paramEngBlueprintId);
		if (result != null) {
			
			ret = dataMapper.mapFromRow(result.get(0), DBEngBlueprintBean.class);
			
		}
		return ret;
	}
	
	public int updateByPrimaryKey(DBEngBlueprintBean bean, java.lang.Long paramEngBlueprintId) throws SQLException, IllegalArgumentException, IllegalAccessException {
		setNames();
		 Map<String, Object> map = dataMapper.mapToRow(bean);
		 Map<String, Object> keys = new HashMap<String, Object>();
		 
		 keys.put("eng_blueprint_id",  paramEngBlueprintId);
		 
		return getConnection().updateRow("eng_blueprint", map, keys);
	}
	
	public int deleteByPrimaryKey(java.lang.Long paramEngBlueprintId) throws SQLException {
		setNames();
		String sql = "DELETE FROM " + tablename + " WHERE  1=1  AND  eng_blueprint_id= ?  ";
		return getConnection().query(sql, paramEngBlueprintId);
	}
	
}