/**
 *  Autogenerated class
 */
package org.c3s.edgo.common.access;

import java.sql.SQLException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import org.c3s.db.access.Access;
import org.c3s.db.*;
import org.c3s.db.beans.*;
import org.c3s.db.injectors.SqlInjectorInterface;
import org.c3s.db.injectors.EmptySqlInjector;
import org.c3s.data.mapers.*;
import org.c3s.data.cast.*;


import org.c3s.edgo.common.beans.*;


@SuppressWarnings("unused")
public class DBImageTumbnailsAccess extends Access {
	protected DBConnection getConnection() {
		setNames();
		return getCon();
	}
	
	private DataMapper dataMapper = new GeneralDataMapper(new GeneralCastType()); 
	
	protected void setNames() {
		con_name = "edgo";
		tablename = "image_tumbnails";
	}
	
	
	public int insert(DBImageTumbnailsBean bean) throws SQLException, IllegalArgumentException, IllegalAccessException {
		setNames();
		int res = _insert(bean);
		bean.setAutoincrementField(res);
		return res;
	}

	
	public List<DBImageTumbnailsBean> getTableRecords() throws SQLException, IllegalArgumentException, IllegalAccessException, InstantiationException {
		return getTableRecords(null);
	}
	public List<DBImageTumbnailsBean> getTableRecords(SqlInjectorInterface injector) throws SQLException, IllegalArgumentException, IllegalAccessException, InstantiationException {
		setNames();
		List<Map<String, Object>> result = _getTableRecords(injector);
		
		List<DBImageTumbnailsBean> ret = null;
		if (result != null) {
			ret = new ArrayList<DBImageTumbnailsBean>();
			for (Map<String, Object> res : result) {
				DBImageTumbnailsBean bean = dataMapper.mapFromRow(res, DBImageTumbnailsBean.class);
				
				ret.add(bean);
			}
		}
		return ret;
	}
	
	
	public DBImageTumbnailsBean getByPrimaryKey(java.lang.Long paramTumbnailId)  throws SQLException, IllegalArgumentException, IllegalAccessException, InstantiationException {
		setNames();
		DBImageTumbnailsBean ret = null;
		SqlInjectorInterface injector = new EmptySqlInjector();
		
		String sql = "SELECT t.* "+injector.getRecordQuery()+" FROM " + tablename + " as t "+injector.getFromQuery()+" WHERE 1=1  AND  tumbnail_id= ?  "+injector.getWhereQuery()+" ";
		if (injector.getOrderQuery().length() != 0) {
			sql += injector.getOrderQuery();
		} else { 
			
		}
		String limit = injector.getLimitQuery();
		if (limit.length() != 0) {
			sql += limit;
		} else {
			sql += " LIMIT 1";
		}
		
		
		
		
		List<Map<String, Object>> result = getConnection().fetchRows(tablename + ".getByPrimaryKey", sql ,  paramTumbnailId);
		if (result != null) {
			
			ret = dataMapper.mapFromRow(result.get(0), DBImageTumbnailsBean.class);
			
		}
		return ret;
	}
	
	public int updateByPrimaryKey(DBImageTumbnailsBean bean, java.lang.Long paramTumbnailId) throws SQLException, IllegalArgumentException, IllegalAccessException {
		setNames();
		 Map<String, Object> map = dataMapper.mapToRow(bean);
		 Map<String, Object> keys = new HashMap<String, Object>();
		 
		 keys.put("tumbnail_id",  paramTumbnailId);
		 
		return getConnection().updateRow("image_tumbnails", map, keys);
	}
	
	public int deleteByPrimaryKey(java.lang.Long paramTumbnailId) throws SQLException {
		setNames();
		String sql = "DELETE FROM " + tablename + " WHERE  1=1  AND  tumbnail_id= ?  ";
		return getConnection().query(sql, paramTumbnailId);
	}
	
	public List<DBTumbnailsForImageBean> getTumbnailsForImage(org.c3s.edgo.common.intruders.InInjector paramIntruder) throws SQLException, IllegalArgumentException, IllegalAccessException, InstantiationException {
		setNames();
		SqlInjectorInterface injector = new EmptySqlInjector();
		
		if (paramIntruder != null) {
			injector = paramIntruder;
		}
		
		
		String query = injector.getFullQuery();
		if (query == null) {
			String record = injector.getRecordQuery();
			String from = injector.getFromQuery();
			String join = injector.getJoinQuery();
			String where = injector.getWhereQuery();
			String order = injector.getOrderQuery();
			String limit = injector.getLimitQuery();
			query = " 				SELECT t.*, c.config_name, LOWER(c.type) as type 				FROM image_tumbnails t, image_configs c 				WHERE 1=1 				" + where + " 				AND c.config_id = t.config_id 				ORDER BY t.image_id, c.config_name 			";
		}

		
		List<Map<String, Object>> result = getConnection().fetchRows(tablename + ".getTumbnailsForImage", query );
		List<DBTumbnailsForImageBean> ret = null;
		if (result != null) {
					ret = new ArrayList<DBTumbnailsForImageBean>();
				
			for (Map<String, Object> res : result) {
				DBTumbnailsForImageBean bean = dataMapper.mapFromRow(res, DBTumbnailsForImageBean.class);
														
				ret.add(bean);
			}
					
		}
			
		return ret;
	}
	
}