/**
 *  Autogenerated class
 */
package org.c3s.edgo.common.access;

import java.sql.SQLException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import org.c3s.db.access.Access;
import org.c3s.db.*;
import org.c3s.db.beans.*;
import org.c3s.db.injectors.SqlInjectorInterface;
import org.c3s.db.injectors.EmptySqlInjector;
import org.c3s.data.mapers.*;
import org.c3s.data.cast.*;


import org.c3s.edgo.common.beans.*;


@SuppressWarnings("unused")
public class DBModulesAccess extends Access {
	protected DBConnection getConnection() {
		setNames();
		return getCon();
	}
	
	private DataMapper dataMapper = new GeneralDataMapper(new GeneralCastType()); 
	
	protected void setNames() {
		con_name = "edgo";
		tablename = "modules";
	}
	
	
	public int insert(DBModulesBean bean) throws SQLException, IllegalArgumentException, IllegalAccessException {
		setNames();
		int res = _insert(bean);
		bean.setAutoincrementField(res);
		return res;
	}

	
	public List<DBModulesBean> getTableRecords() throws SQLException, IllegalArgumentException, IllegalAccessException, InstantiationException {
		return getTableRecords(null);
	}
	public List<DBModulesBean> getTableRecords(SqlInjectorInterface injector) throws SQLException, IllegalArgumentException, IllegalAccessException, InstantiationException {
		setNames();
		List<Map<String, Object>> result = _getTableRecords(injector);
		
		List<DBModulesBean> ret = null;
		if (result != null) {
			ret = new ArrayList<DBModulesBean>();
			for (Map<String, Object> res : result) {
				DBModulesBean bean = dataMapper.mapFromRow(res, DBModulesBean.class);
				
				ret.add(bean);
			}
		}
		return ret;
	}
	
	
	public DBModulesBean getByPrimaryKey(java.lang.Long paramModuleId)  throws SQLException, IllegalArgumentException, IllegalAccessException, InstantiationException {
		setNames();
		DBModulesBean ret = null;
		SqlInjectorInterface injector = new EmptySqlInjector();
		
		String sql = "SELECT t.* "+injector.getRecordQuery()+" FROM " + tablename + " as t "+injector.getFromQuery()+" WHERE 1=1  AND  module_id= ?  "+injector.getWhereQuery()+" ";
		if (injector.getOrderQuery().length() != 0) {
			sql += injector.getOrderQuery();
		} else { 
			
		}
		String limit = injector.getLimitQuery();
		if (limit.length() != 0) {
			sql += limit;
		} else {
			sql += " LIMIT 1";
		}
		
		
		
		
		List<Map<String, Object>> result = getConnection().fetchRows(tablename + ".getByPrimaryKey", sql ,  paramModuleId);
		if (result != null) {
			
			ret = dataMapper.mapFromRow(result.get(0), DBModulesBean.class);
			
		}
		return ret;
	}
	
	public int updateByPrimaryKey(DBModulesBean bean, java.lang.Long paramModuleId) throws SQLException, IllegalArgumentException, IllegalAccessException {
		setNames();
		 Map<String, Object> map = dataMapper.mapToRow(bean);
		 Map<String, Object> keys = new HashMap<String, Object>();
		 
		 keys.put("module_id",  paramModuleId);
		 
		return getConnection().updateRow("modules", map, keys);
	}
	
	public int deleteByPrimaryKey(java.lang.Long paramModuleId) throws SQLException {
		setNames();
		String sql = "DELETE FROM " + tablename + " WHERE  1=1  AND  module_id= ?  ";
		return getConnection().query(sql, paramModuleId);
	}
	
	public DBByModuleInfoByUniqBean getByModuleInfoByUniq(String paramUniq) throws SQLException, IllegalArgumentException, IllegalAccessException, InstantiationException {
		setNames();
		SqlInjectorInterface injector = new EmptySqlInjector();
		
		
		String query = injector.getFullQuery();
		if (query == null) {
			String record = injector.getRecordQuery();
			String from = injector.getFromQuery();
			String join = injector.getJoinQuery();
			String where = injector.getWhereQuery();
			String order = injector.getOrderQuery();
			String limit = injector.getLimitQuery();
			query = " 				SELECT m.*, g.*, t.* 				FROM modules m, module_groups g, slot_types t 				WHERE LOWER(m.module_uniq) = ? 				AND g.module_group_id = m.module_group_id 				AND t.slot_type_id = g.slot_type_id 				LIMIT 1 			";
		}

		
		List<Map<String, Object>> result = getConnection().fetchRows(tablename + ".getByModuleInfoByUniq", query ,  paramUniq);
		DBByModuleInfoByUniqBean ret = null;
		if (result != null) {
					ret = new DBByModuleInfoByUniqBean();
				
					ret = dataMapper.mapFromRow(result.get(0), DBByModuleInfoByUniqBean.class);
					
		}
			
		return ret;
	}
	
	public DBModulesBean getByUniq(String paramUniq) throws SQLException, IllegalArgumentException, IllegalAccessException, InstantiationException {
		setNames();
		SqlInjectorInterface injector = new EmptySqlInjector();
		
		
		String query = injector.getFullQuery();
		if (query == null) {
			String record = injector.getRecordQuery();
			String from = injector.getFromQuery();
			String join = injector.getJoinQuery();
			String where = injector.getWhereQuery();
			String order = injector.getOrderQuery();
			String limit = injector.getLimitQuery();
			query = " 				SELECT m.* 				FROM modules m 				WHERE LOWER(m.module_uniq) = ? 				LIMIT 1 			";
		}

		
		List<Map<String, Object>> result = getConnection().fetchRows(tablename + ".getByUniq", query ,  paramUniq);
		DBModulesBean ret = null;
		if (result != null) {
					ret = new DBModulesBean();
				
					ret = dataMapper.mapFromRow(result.get(0), DBModulesBean.class);
					
		}
			
		return ret;
	}
	
}