/**
 *  Autogenerated class
 */
package org.c3s.edgo.common.access;

import java.sql.SQLException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import org.c3s.db.access.Access;
import org.c3s.db.*;
import org.c3s.db.beans.*;
import org.c3s.db.injectors.SqlInjectorInterface;
import org.c3s.db.injectors.EmptySqlInjector;
import org.c3s.data.mapers.*;
import org.c3s.data.cast.*;
import org.c3s.edgo.utils.cast.EdGoCast;


import org.c3s.edgo.common.beans.*;


@SuppressWarnings("unused")
public class DBPilotPowerAccess extends Access {
	protected DBConnection getConnection() {
		setNames();
		return getCon();
	}
	
	private DataMapper dataMapper = new GeneralDataMapper(new EdGoCast()); 
	
	protected void setNames() {
		con_name = "edgo";
		tablename = "pilot_power";
	}
	
	
	public int insert(DBPilotPowerBean bean) throws SQLException, IllegalArgumentException, IllegalAccessException {
		setNames();
		int res = _insert(bean);
		bean.setAutoincrementField(res);
		return res;
	}

	
	public List<DBPilotPowerBean> getTableRecords() throws SQLException, IllegalArgumentException, IllegalAccessException, InstantiationException {
		return getTableRecords(null);
	}
	public List<DBPilotPowerBean> getTableRecords(SqlInjectorInterface injector) throws SQLException, IllegalArgumentException, IllegalAccessException, InstantiationException {
		setNames();
		List<Map<String, Object>> result = _getTableRecords(injector);
		
		List<DBPilotPowerBean> ret = null;
		if (result != null) {
			ret = new ArrayList<DBPilotPowerBean>();
			for (Map<String, Object> res : result) {
				DBPilotPowerBean bean = dataMapper.mapFromRow(res, DBPilotPowerBean.class);
				
				ret.add(bean);
			}
		}
		return ret;
	}
	
	
	public DBPilotPowerBean getLastByPilotId(java.lang.Long paramPilotId)  throws SQLException, IllegalArgumentException, IllegalAccessException, InstantiationException {
		setNames();
		DBPilotPowerBean ret = null;
		SqlInjectorInterface injector = new EmptySqlInjector();
		
		String sql = "SELECT t.* "+injector.getRecordQuery()+" FROM " + tablename + " as t "+injector.getFromQuery()+" WHERE 1=1  AND  pilot_id= ?  "+injector.getWhereQuery()+" ";
		if (injector.getOrderQuery().length() != 0) {
			sql += injector.getOrderQuery();
		} else { 
			sql += "ORDER BY pilot_power_time ASC";
			
		}
		String limit = injector.getLimitQuery();
		if (limit.length() != 0) {
			sql += limit;
		} else {
			sql += " LIMIT 1";
		}
		
		
		
		
		List<Map<String, Object>> result = getConnection().fetchRows(tablename + ".getLastByPilotId", sql ,  paramPilotId);
		if (result != null) {
			
			ret = dataMapper.mapFromRow(result.get(0), DBPilotPowerBean.class);
			
		}
		return ret;
	}
	
	public List<DBPilotPowerBean> getHistoryByPilotId(java.lang.Long paramPilotId)  throws SQLException, IllegalArgumentException, IllegalAccessException, InstantiationException {
		setNames();
		List<DBPilotPowerBean> ret = null;
		SqlInjectorInterface injector = new EmptySqlInjector();
		
		String sql = "SELECT t.* "+injector.getRecordQuery()+" FROM " + tablename + " as t "+injector.getFromQuery()+" WHERE 1=1  AND  pilot_id= ?  "+injector.getWhereQuery()+" ";
		if (injector.getOrderQuery().length() != 0) {
			sql += injector.getOrderQuery();
		} else { 
			sql += "ORDER BY pilot_power_time ASC";
			
		}
		String limit = injector.getLimitQuery();
		if (limit.length() != 0) {
			sql += limit;
		} else {
			
		}
		
		
		
		
		List<Map<String, Object>> result = getConnection().fetchRows(tablename + ".getHistoryByPilotId", sql ,  paramPilotId);
		if (result != null) {
			
			ret = new ArrayList<DBPilotPowerBean>();
			for (Map<String, Object> res : result) {
				DBPilotPowerBean bean = dataMapper.mapFromRow(res, DBPilotPowerBean.class);
				 
				ret.add(bean);
			}
				
		}
		return ret;
	}
	
	public DBPilotPowerBean getLastByPilotIdTime(java.lang.Long paramPilotId, java.sql.Timestamp paramPilotPowerTime)  throws SQLException, IllegalArgumentException, IllegalAccessException, InstantiationException {
		setNames();
		DBPilotPowerBean ret = null;
		SqlInjectorInterface injector = new EmptySqlInjector();
		
		String sql = "SELECT t.* "+injector.getRecordQuery()+" FROM " + tablename + " as t "+injector.getFromQuery()+" WHERE 1=1  AND  pilot_id= ?  AND  pilot_power_time<= ?  "+injector.getWhereQuery()+" ";
		if (injector.getOrderQuery().length() != 0) {
			sql += injector.getOrderQuery();
		} else { 
			sql += "ORDER BY pilot_power_time DESC";
			
		}
		String limit = injector.getLimitQuery();
		if (limit.length() != 0) {
			sql += limit;
		} else {
			sql += " LIMIT 1";
		}
		
		
		
		
		List<Map<String, Object>> result = getConnection().fetchRows(tablename + ".getLastByPilotIdTime", sql ,  paramPilotId,  paramPilotPowerTime);
		if (result != null) {
			
			ret = dataMapper.mapFromRow(result.get(0), DBPilotPowerBean.class);
			
		}
		return ret;
	}
	
	public DBPilotPowerBean getByPrimaryKey(java.lang.Long paramPilotPowerId)  throws SQLException, IllegalArgumentException, IllegalAccessException, InstantiationException {
		setNames();
		DBPilotPowerBean ret = null;
		SqlInjectorInterface injector = new EmptySqlInjector();
		
		String sql = "SELECT t.* "+injector.getRecordQuery()+" FROM " + tablename + " as t "+injector.getFromQuery()+" WHERE 1=1  AND  pilot_power_id= ?  "+injector.getWhereQuery()+" ";
		if (injector.getOrderQuery().length() != 0) {
			sql += injector.getOrderQuery();
		} else { 
			
		}
		String limit = injector.getLimitQuery();
		if (limit.length() != 0) {
			sql += limit;
		} else {
			sql += " LIMIT 1";
		}
		
		
		
		
		List<Map<String, Object>> result = getConnection().fetchRows(tablename + ".getByPrimaryKey", sql ,  paramPilotPowerId);
		if (result != null) {
			
			ret = dataMapper.mapFromRow(result.get(0), DBPilotPowerBean.class);
			
		}
		return ret;
	}
	
	public int updateByPrimaryKey(DBPilotPowerBean bean, java.lang.Long paramPilotPowerId) throws SQLException, IllegalArgumentException, IllegalAccessException {
		setNames();
		 Map<String, Object> map = dataMapper.mapToRow(bean);
		 Map<String, Object> keys = new HashMap<String, Object>();
		 
		 keys.put("pilot_power_id",  paramPilotPowerId);
		 
		return getConnection().updateRow("pilot_power", map, keys);
	}
	
	public int deleteByPrimaryKey(java.lang.Long paramPilotPowerId) throws SQLException {
		setNames();
		String sql = "DELETE FROM " + tablename + " WHERE  1=1  AND  pilot_power_id= ?  ";
		return getConnection().query(sql, paramPilotPowerId);
	}
	
	public List<DBPilotsPowerWeeksBean> getPilotsPowerWeeks(org.c3s.edgo.common.intruders.InInjector paramIntruder) throws SQLException, IllegalArgumentException, IllegalAccessException, InstantiationException {
		setNames();
		SqlInjectorInterface injector = new EmptySqlInjector();
		
		if (paramIntruder != null) {
			injector = paramIntruder;
		}
		
		
		String query = injector.getFullQuery();
		if (query == null) {
			String record = injector.getRecordQuery();
			String from = injector.getFromQuery();
			String join = injector.getJoinQuery();
			String where = injector.getWhereQuery();
			String order = injector.getOrderQuery();
			String limit = injector.getLimitQuery();
			query = " 				SELECT a.start_week FROM ( 				(SELECT DISTINCT start_week FROM pilot_war_merits WHERE 1 = 1 " + where + ") 				UNION DISTINCT 				(SELECT DISTINCT start_week FROM pilot_kill_merits WHERE 1 = 1 " + where + ") 				UNION DISTINCT 				(SELECT DISTINCT start_week FROM pilot_power_spend WHERE 1 = 1 " + where + ") 				UNION DISTINCT 				(SELECT DISTINCT start_week FROM pilot_deliver WHERE 1 = 1 " + where + ") 				ORDER BY start_week DESC) as a 			";
		}

		
		List<Map<String, Object>> result = getConnection().fetchRows(tablename + ".getPilotsPowerWeeks", query );
		List<DBPilotsPowerWeeksBean> ret = null;
		if (result != null) {
					ret = new ArrayList<DBPilotsPowerWeeksBean>();
				
			for (Map<String, Object> res : result) {
				DBPilotsPowerWeeksBean bean = dataMapper.mapFromRow(res, DBPilotsPowerWeeksBean.class);
														
				ret.add(bean);
			}
					
		}
			
		return ret;
	}
	
}