/**
 *  Autogenerated class
 */
package org.c3s.edgo.common.access;

import java.sql.SQLException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import org.c3s.db.access.Access;
import org.c3s.db.*;
import org.c3s.db.beans.*;
import org.c3s.db.injectors.SqlInjectorInterface;
import org.c3s.db.injectors.EmptySqlInjector;
import org.c3s.data.mapers.*;
import org.c3s.data.cast.*;


import org.c3s.edgo.common.beans.*;


@SuppressWarnings("unused")
public class DBPowersAccess extends Access {
	protected DBConnection getConnection() {
		setNames();
		return getCon();
	}
	
	private DataMapper dataMapper = new GeneralDataMapper(new GeneralCastType()); 
	
	protected void setNames() {
		con_name = "edgo";
		tablename = "powers";
	}
	
	
	public int insert(DBPowersBean bean) throws SQLException, IllegalArgumentException, IllegalAccessException {
		setNames();
		int res = _insert(bean);
		bean.setAutoincrementField(res);
		return res;
	}

	
	public List<DBPowersBean> getTableRecords() throws SQLException, IllegalArgumentException, IllegalAccessException, InstantiationException {
		return getTableRecords(null);
	}
	public List<DBPowersBean> getTableRecords(SqlInjectorInterface injector) throws SQLException, IllegalArgumentException, IllegalAccessException, InstantiationException {
		setNames();
		List<Map<String, Object>> result = _getTableRecords(injector);
		
		List<DBPowersBean> ret = null;
		if (result != null) {
			ret = new ArrayList<DBPowersBean>();
			for (Map<String, Object> res : result) {
				DBPowersBean bean = dataMapper.mapFromRow(res, DBPowersBean.class);
				
				ret.add(bean);
			}
		}
		return ret;
	}
	
	
	public DBPowersBean getByUniq(java.lang.String paramPowerUniq)  throws SQLException, IllegalArgumentException, IllegalAccessException, InstantiationException {
		setNames();
		DBPowersBean ret = null;
		SqlInjectorInterface injector = new EmptySqlInjector();
		
		String sql = "SELECT t.* "+injector.getRecordQuery()+" FROM " + tablename + " as t "+injector.getFromQuery()+" WHERE 1=1 AND  power_uniq= ?  "+injector.getWhereQuery()+" ";
		if (injector.getOrderQuery().length() != 0) {
			sql += injector.getOrderQuery();
		} else { 
			
		}
		sql += injector.getLimitQuery();
		List<Map<String, Object>> result = getConnection().fetchRows(tablename + ".getByUniq", sql ,  paramPowerUniq);
		if (result != null) {
			
			ret = dataMapper.mapFromRow(result.get(0), DBPowersBean.class);
			
		}
		return ret;
	}
	
	public DBPowersBean getByPrimaryKey(java.lang.Long paramPowerId)  throws SQLException, IllegalArgumentException, IllegalAccessException, InstantiationException {
		setNames();
		DBPowersBean ret = null;
		SqlInjectorInterface injector = new EmptySqlInjector();
		
		String sql = "SELECT t.* "+injector.getRecordQuery()+" FROM " + tablename + " as t "+injector.getFromQuery()+" WHERE 1=1 AND  power_id= ?  "+injector.getWhereQuery()+" ";
		if (injector.getOrderQuery().length() != 0) {
			sql += injector.getOrderQuery();
		} else { 
			
		}
		sql += injector.getLimitQuery();
		List<Map<String, Object>> result = getConnection().fetchRows(tablename + ".getByPrimaryKey", sql ,  paramPowerId);
		if (result != null) {
			
			ret = dataMapper.mapFromRow(result.get(0), DBPowersBean.class);
			
		}
		return ret;
	}
	
	public int updateByPrimaryKey(DBPowersBean bean, java.lang.Long paramPowerId) throws SQLException, IllegalArgumentException, IllegalAccessException {
		setNames();
		 Map<String, Object> map = dataMapper.mapToRow(bean);
		 Map<String, Object> keys = new HashMap<String, Object>();
		 
		 keys.put("power_id",  paramPowerId);
		 
		return getConnection().updateRow("powers", map, keys);
	}
	
	public int deleteByPrimaryKey(java.lang.Long paramPowerId) throws SQLException {
		setNames();
		String sql = "DELETE FROM " + tablename + " WHERE  1=1 AND  power_id= ?  ";
		return getConnection().query(sql, paramPowerId);
	}
	
	public DBPowersBean getByUniqOrAlias(String paramUniq, String paramAlias) throws SQLException, IllegalArgumentException, IllegalAccessException, InstantiationException {
		setNames();
		SqlInjectorInterface injector = new EmptySqlInjector();
		
		
		String query = injector.getFullQuery();
		if (query == null) {
			String record = injector.getRecordQuery();
			String from = injector.getRecordQuery();
			String join = injector.getRecordQuery();
			String where = injector.getRecordQuery();
			String order = injector.getRecordQuery();
			String limit = injector.getRecordQuery();
			query = " 				SELECT p.* 				FROM powers p 				WHERE p.power_uniq = ? 				OR p.power_aliases LIKE CONCAT('%', ?, '%') 				LIMIT 1 			";
		}

		
		List<Map<String, Object>> result = getConnection().fetchRows(tablename + ".getByUniqOrAlias", query ,  paramUniq,  paramAlias);
		DBPowersBean ret = null;
		if (result != null) {
					ret = new DBPowersBean();
				
					ret = dataMapper.mapFromRow(result.get(0), DBPowersBean.class);
					
		}
			
		return ret;
	}
	
}