/**
 *  Autogenerated class
 */
package org.c3s.edgo.common.access;

import java.sql.SQLException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import org.c3s.db.access.Access;
import org.c3s.db.*;
import org.c3s.db.beans.*;
import org.c3s.db.injectors.SqlInjectorInterface;
import org.c3s.db.injectors.EmptySqlInjector;
import org.c3s.data.mapers.*;
import org.c3s.data.cast.*;


import org.c3s.edgo.common.beans.*;


@SuppressWarnings("unused")
public class DBPowerStateTypeAccess extends Access {
	protected DBConnection getConnection() {
		setNames();
		return getCon();
	}
	
	private DataMapper dataMapper = new GeneralDataMapper(new GeneralCastType()); 
	
	protected void setNames() {
		con_name = "edgo";
		tablename = "power_state_type";
	}
	
	
	public int insert(DBPowerStateTypeBean bean) throws SQLException, IllegalArgumentException, IllegalAccessException {
		setNames();
		int res = _insert(bean);
		bean.setAutoincrementField(res);
		return res;
	}

	
	public List<DBPowerStateTypeBean> getTableRecords() throws SQLException, IllegalArgumentException, IllegalAccessException, InstantiationException {
		return getTableRecords(null);
	}
	public List<DBPowerStateTypeBean> getTableRecords(SqlInjectorInterface injector) throws SQLException, IllegalArgumentException, IllegalAccessException, InstantiationException {
		setNames();
		List<Map<String, Object>> result = _getTableRecords(injector);
		
		List<DBPowerStateTypeBean> ret = null;
		if (result != null) {
			ret = new ArrayList<DBPowerStateTypeBean>();
			for (Map<String, Object> res : result) {
				DBPowerStateTypeBean bean = dataMapper.mapFromRow(res, DBPowerStateTypeBean.class);
				
				ret.add(bean);
			}
		}
		return ret;
	}
	
	
	public DBPowerStateTypeBean getByUniq(java.lang.String paramPowerStateTypeUniq)  throws SQLException, IllegalArgumentException, IllegalAccessException, InstantiationException {
		setNames();
		DBPowerStateTypeBean ret = null;
		SqlInjectorInterface injector = new EmptySqlInjector();
		
		String sql = "SELECT t.* "+injector.getRecordQuery()+" FROM " + tablename + " as t "+injector.getFromQuery()+" WHERE 1=1 AND  power_state_type_uniq= ?  "+injector.getWhereQuery()+" ";
		if (injector.getOrderQuery().length() != 0) {
			sql += injector.getOrderQuery();
		} else { 
			
		}
		sql += injector.getLimitQuery();
		List<Map<String, Object>> result = getConnection().fetchRows(tablename + ".getByUniq", sql ,  paramPowerStateTypeUniq);
		if (result != null) {
			
			ret = dataMapper.mapFromRow(result.get(0), DBPowerStateTypeBean.class);
			
		}
		return ret;
	}
	
	public DBPowerStateTypeBean getByPrimaryKey(java.lang.Long paramPowerStateTypeId)  throws SQLException, IllegalArgumentException, IllegalAccessException, InstantiationException {
		setNames();
		DBPowerStateTypeBean ret = null;
		SqlInjectorInterface injector = new EmptySqlInjector();
		
		String sql = "SELECT t.* "+injector.getRecordQuery()+" FROM " + tablename + " as t "+injector.getFromQuery()+" WHERE 1=1 AND  power_state_type_id= ?  "+injector.getWhereQuery()+" ";
		if (injector.getOrderQuery().length() != 0) {
			sql += injector.getOrderQuery();
		} else { 
			
		}
		sql += injector.getLimitQuery();
		List<Map<String, Object>> result = getConnection().fetchRows(tablename + ".getByPrimaryKey", sql ,  paramPowerStateTypeId);
		if (result != null) {
			
			ret = dataMapper.mapFromRow(result.get(0), DBPowerStateTypeBean.class);
			
		}
		return ret;
	}
	
	public int updateByPrimaryKey(DBPowerStateTypeBean bean, java.lang.Long paramPowerStateTypeId) throws SQLException, IllegalArgumentException, IllegalAccessException {
		setNames();
		 Map<String, Object> map = dataMapper.mapToRow(bean);
		 Map<String, Object> keys = new HashMap<String, Object>();
		 
		 keys.put("power_state_type_id",  paramPowerStateTypeId);
		 
		return getConnection().updateRow("power_state_type", map, keys);
	}
	
	public int deleteByPrimaryKey(java.lang.Long paramPowerStateTypeId) throws SQLException {
		setNames();
		String sql = "DELETE FROM " + tablename + " WHERE  1=1 AND  power_state_type_id= ?  ";
		return getConnection().query(sql, paramPowerStateTypeId);
	}
	
}