/**
 *  Autogenerated class
 */
package org.c3s.edgo.common.access;

import java.sql.SQLException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import org.c3s.db.access.Access;
import org.c3s.db.*;
import org.c3s.db.beans.*;
import org.c3s.db.injectors.SqlInjectorInterface;
import org.c3s.db.injectors.EmptySqlInjector;
import org.c3s.data.mapers.*;
import org.c3s.data.cast.*;
import org.c3s.edgo.utils.cast.EdGoCast;


import org.c3s.edgo.common.beans.*;


@SuppressWarnings("unused")
public class DBSettlementsAccess extends Access {
	protected DBConnection getConnection() {
		setNames();
		return getCon();
	}
	
	private DataMapper dataMapper = new GeneralDataMapper(new EdGoCast()); 
	
	protected void setNames() {
		con_name = "edgo";
		tablename = "settlements";
	}
	
	
	public int insert(DBSettlementsBean bean) throws SQLException, IllegalArgumentException, IllegalAccessException {
		setNames();
		int res = _insert(bean);
		bean.setAutoincrementField(res);
		return res;
	}

	
	public List<DBSettlementsBean> getTableRecords() throws SQLException, IllegalArgumentException, IllegalAccessException, InstantiationException {
		return getTableRecords(null);
	}
	public List<DBSettlementsBean> getTableRecords(SqlInjectorInterface injector) throws SQLException, IllegalArgumentException, IllegalAccessException, InstantiationException {
		setNames();
		List<Map<String, Object>> result = _getTableRecords(injector);
		
		List<DBSettlementsBean> ret = null;
		if (result != null) {
			ret = new ArrayList<DBSettlementsBean>();
			for (Map<String, Object> res : result) {
				DBSettlementsBean bean = dataMapper.mapFromRow(res, DBSettlementsBean.class);
				
				ret.add(bean);
			}
		}
		return ret;
	}
	
	
	public DBSettlementsBean getByPrimaryKey(java.lang.Long paramSettlementId)  throws SQLException, IllegalArgumentException, IllegalAccessException, InstantiationException {
		setNames();
		DBSettlementsBean ret = null;
		SqlInjectorInterface injector = new EmptySqlInjector();
		
		String sql = "SELECT t.* "+injector.getRecordQuery()+" FROM " + tablename + " as t "+injector.getFromQuery()+" WHERE 1=1  AND  settlement_id= ?  "+injector.getWhereQuery()+" ";
		if (injector.getOrderQuery().length() != 0) {
			sql += injector.getOrderQuery();
		} else { 
			
		}
		String limit = injector.getLimitQuery();
		if (limit.length() != 0) {
			sql += limit;
		} else {
			sql += " LIMIT 1";
		}
		
		
		
		
		List<Map<String, Object>> result = getConnection().fetchRows(tablename + ".getByPrimaryKey", sql ,  paramSettlementId);
		if (result != null) {
			
			ret = dataMapper.mapFromRow(result.get(0), DBSettlementsBean.class);
			
		}
		return ret;
	}
	
	public int updateByPrimaryKey(DBSettlementsBean bean, java.lang.Long paramSettlementId) throws SQLException, IllegalArgumentException, IllegalAccessException {
		setNames();
		 Map<String, Object> map = dataMapper.mapToRow(bean);
		 Map<String, Object> keys = new HashMap<String, Object>();
		 
		 keys.put("settlement_id",  paramSettlementId);
		 
		return getConnection().updateRow("settlements", map, keys);
	}
	
	public DBCountBySystemAndNameBean getCountBySystemAndName(java.math.BigInteger paramsystem_id, String paramname) throws SQLException, IllegalArgumentException, IllegalAccessException, InstantiationException {
		setNames();
		SqlInjectorInterface injector = new EmptySqlInjector();
		
		
		String query = injector.getFullQuery();
		if (query == null) {
			String record = injector.getRecordQuery();
			String from = injector.getFromQuery();
			String join = injector.getJoinQuery();
			String where = injector.getWhereQuery();
			String order = injector.getOrderQuery();
			String limit = injector.getLimitQuery();
			query = " 				SELECT COUNT(st.settlement_id) AS count 				FROM settlements st 				WHERE st.system_id = ? 				AND LOWER(st.name) = ? 				LIMIT 1 			";
		}

		
		List<Map<String, Object>> result = getConnection().fetchRows(tablename + ".getCountBySystemAndName", query ,  paramsystem_id,  paramname);
		DBCountBySystemAndNameBean ret = null;
		if (result != null) {
					ret = new DBCountBySystemAndNameBean();
				
					ret = dataMapper.mapFromRow(result.get(0), DBCountBySystemAndNameBean.class);
					
		}
			
		return ret;
	}
	
	public List<DBSettlementsSearchBean> getSettlementsSearch(org.c3s.db.injectors.EmptySqlInjector paramIntruder) throws SQLException, IllegalArgumentException, IllegalAccessException, InstantiationException {
		setNames();
		SqlInjectorInterface injector = new EmptySqlInjector();
		
		if (paramIntruder != null) {
			injector = paramIntruder;
		}
		
		
		String query = injector.getFullQuery();
		if (query == null) {
			String record = injector.getRecordQuery();
			String from = injector.getFromQuery();
			String join = injector.getJoinQuery();
			String where = injector.getWhereQuery();
			String order = injector.getOrderQuery();
			String limit = injector.getLimitQuery();
			query = " 				SELECT t.title, st.*, s.name as system_name, s.x, s.y, s.z 				FROM settlement_types t, settlements st, systems s 				WHERE 1=1 				" + where + " 				AND t.settlement_type_id = st.settlement_type_id 				AND st.system_id = s.system_id      			";
		}

		
		List<Map<String, Object>> result = getConnection().fetchRows(tablename + ".getSettlementsSearch", query );
		List<DBSettlementsSearchBean> ret = null;
		if (result != null) {
					ret = new ArrayList<DBSettlementsSearchBean>();
				
			for (Map<String, Object> res : result) {
				DBSettlementsSearchBean bean = dataMapper.mapFromRow(res, DBSettlementsSearchBean.class);
														
				ret.add(bean);
			}
					
		}
			
		return ret;
	}
	
}