/**
 *  Autogenerated class
 */
package org.c3s.edgo.common.access;

import java.sql.SQLException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import org.c3s.db.access.Access;
import org.c3s.db.*;
import org.c3s.db.beans.*;
import org.c3s.db.injectors.SqlInjectorInterface;
import org.c3s.db.injectors.EmptySqlInjector;
import org.c3s.data.mapers.*;
import org.c3s.data.cast.*;
import org.c3s.edgo.utils.cast.EdGoCast;


import org.c3s.edgo.common.beans.*;


@SuppressWarnings("unused")
public class DBSlotsAccess extends Access {
	protected DBConnection getConnection() {
		setNames();
		return getCon();
	}
	
	private DataMapper dataMapper = new GeneralDataMapper(new EdGoCast()); 
	
	protected void setNames() {
		con_name = "edgo";
		tablename = "slots";
	}
	
	
	public int insert(DBSlotsBean bean) throws SQLException, IllegalArgumentException, IllegalAccessException {
		setNames();
		int res = _insert(bean);
		bean.setAutoincrementField(res);
		return res;
	}

	
	public List<DBSlotsBean> getTableRecords() throws SQLException, IllegalArgumentException, IllegalAccessException, InstantiationException {
		return getTableRecords(null);
	}
	public List<DBSlotsBean> getTableRecords(SqlInjectorInterface injector) throws SQLException, IllegalArgumentException, IllegalAccessException, InstantiationException {
		setNames();
		List<Map<String, Object>> result = _getTableRecords(injector);
		
		List<DBSlotsBean> ret = null;
		if (result != null) {
			ret = new ArrayList<DBSlotsBean>();
			for (Map<String, Object> res : result) {
				DBSlotsBean bean = dataMapper.mapFromRow(res, DBSlotsBean.class);
				
				ret.add(bean);
			}
		}
		return ret;
	}
	
	
	public DBSlotsBean getByUniq(java.lang.String paramSlotUniq)  throws SQLException, IllegalArgumentException, IllegalAccessException, InstantiationException {
		setNames();
		DBSlotsBean ret = null;
		SqlInjectorInterface injector = new EmptySqlInjector();
		
		String sql = "SELECT t.* "+injector.getRecordQuery()+" FROM " + tablename + " as t "+injector.getFromQuery()+" WHERE 1=1  AND  slot_uniq= ?  "+injector.getWhereQuery()+" ";
		if (injector.getOrderQuery().length() != 0) {
			sql += injector.getOrderQuery();
		} else { 
			
		}
		String limit = injector.getLimitQuery();
		if (limit.length() != 0) {
			sql += limit;
		} else {
			sql += " LIMIT 1";
		}
		
		
		
		
		List<Map<String, Object>> result = getConnection().fetchRows(tablename + ".getByUniq", sql ,  paramSlotUniq);
		if (result != null) {
			
			ret = dataMapper.mapFromRow(result.get(0), DBSlotsBean.class);
			
		}
		return ret;
	}
	
	public DBSlotsBean getByPrimaryKey(java.lang.Long paramSlotId)  throws SQLException, IllegalArgumentException, IllegalAccessException, InstantiationException {
		setNames();
		DBSlotsBean ret = null;
		SqlInjectorInterface injector = new EmptySqlInjector();
		
		String sql = "SELECT t.* "+injector.getRecordQuery()+" FROM " + tablename + " as t "+injector.getFromQuery()+" WHERE 1=1  AND  slot_id= ?  "+injector.getWhereQuery()+" ";
		if (injector.getOrderQuery().length() != 0) {
			sql += injector.getOrderQuery();
		} else { 
			
		}
		String limit = injector.getLimitQuery();
		if (limit.length() != 0) {
			sql += limit;
		} else {
			sql += " LIMIT 1";
		}
		
		
		
		
		List<Map<String, Object>> result = getConnection().fetchRows(tablename + ".getByPrimaryKey", sql ,  paramSlotId);
		if (result != null) {
			
			ret = dataMapper.mapFromRow(result.get(0), DBSlotsBean.class);
			
		}
		return ret;
	}
	
	public int updateByPrimaryKey(DBSlotsBean bean, java.lang.Long paramSlotId) throws SQLException, IllegalArgumentException, IllegalAccessException {
		setNames();
		 Map<String, Object> map = dataMapper.mapToRow(bean);
		 Map<String, Object> keys = new HashMap<String, Object>();
		 
		 keys.put("slot_id",  paramSlotId);
		 
		return getConnection().updateRow("slots", map, keys);
	}
	
	public int deleteByPrimaryKey(java.lang.Long paramSlotId) throws SQLException {
		setNames();
		String sql = "DELETE FROM " + tablename + " WHERE  1=1  AND  slot_id= ?  ";
		return getConnection().query(sql, paramSlotId);
	}
	
	public List<DBShipSlotsByShipUniqBean> getShipSlotsByShipUniq(String paramUniq) throws SQLException, IllegalArgumentException, IllegalAccessException, InstantiationException {
		setNames();
		SqlInjectorInterface injector = new EmptySqlInjector();
		
		
		String query = injector.getFullQuery();
		if (query == null) {
			String record = injector.getRecordQuery();
			String from = injector.getFromQuery();
			String join = injector.getJoinQuery();
			String where = injector.getWhereQuery();
			String order = injector.getOrderQuery();
			String limit = injector.getLimitQuery();
			query = " 				SELECT sl.*, st.*, CAST(IF(ISNULL(ss.link_size), sl.size, ss.link_size) AS CHAR(1)) as link_size, COUNT(DISTINCT pm.pilot_module_id) as used_count, GROUP_CONCAT(DISTINCT m.module_uniq ORDER BY m.module_uniq) as modules 				FROM slots sl, slot_types st, ships s, ship_slots ss 				LEFT JOIN pilot_ships ps ON ps.ship_id = ss.ship_id 				LEFT JOIN pilot_modules pm ON pm.pilot_ship_id = ps.pilot_ship_id AND pm.slot_id = ss.slot_id 				LEFT JOIN modules m ON m.module_id = pm.module_id 				WHERE s.ship_uniq = ? 				AND ss.ship_id = s.ship_id 				AND ss.slot_id = sl.slot_id 				AND sl.slot_type_id = st.slot_type_id 				GROUP BY sl.slot_id, ss.slot_id, ss.ship_id 				ORDER BY st.slot_type_name, sl.slot_uniq ASC 			";
		}

		
		List<Map<String, Object>> result = getConnection().fetchRows(tablename + ".getShipSlotsByShipUniq", query ,  paramUniq);
		List<DBShipSlotsByShipUniqBean> ret = null;
		if (result != null) {
					ret = new ArrayList<DBShipSlotsByShipUniqBean>();
				
			for (Map<String, Object> res : result) {
				DBShipSlotsByShipUniqBean bean = dataMapper.mapFromRow(res, DBShipSlotsByShipUniqBean.class);
														
				ret.add(bean);
			}
					
		}
			
		return ret;
	}
	
}